project_id = "exsbnfmaadjyfblperas"

[functions.admin-ai-assistant]
verify_jwt = false

[functions.platform-assistant]
verify_jwt = false

[functions.setup-vision-plan]
verify_jwt = false

[functions.goal-wizard-ai]
verify_jwt = false

[functions.generate-vision-board-images]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.performance-coach]
verify_jwt = false

[functions.relationship-coach]
verify_jwt = false

[functions.therapist-coach]
verify_jwt = false

[functions.accountability-coach]
verify_jwt = false

[functions.generate-empowerment-meditation]
verify_jwt = false

[functions.send-challenge-reminder]
verify_jwt = false
