project_id = "exsbnfmaadjyfblperas"

[functions.admin-impersonate]
verify_jwt = false

[functions.admin-ai-assistant]
verify_jwt = false

[functions.platform-assistant]
verify_jwt = false

[functions.setup-vision-plan]
verify_jwt = false

[functions.goal-wizard-ai]
verify_jwt = false

[functions.generate-vision-board-images]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.performance-coach]
verify_jwt = false

[functions.relationship-coach]
verify_jwt = false

[functions.therapist-coach]
verify_jwt = false

[functions.accountability-coach]
verify_jwt = false

[functions.generate-empowerment-meditation]
verify_jwt = false

[functions.send-challenge-reminder]
verify_jwt = false

[functions.warrior-ai-coach]
verify_jwt = false

[functions.send-warrior-power-sequence]
verify_jwt = false

[functions.send-power-results]
verify_jwt = false

[functions.unsubscribe-email]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.send-vision-results]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.life-vision-ai]
verify_jwt = false

[functions.door-ai-planning]
verify_jwt = false

[functions.send-goal-plan-email]
verify_jwt = false

[functions.sales-coach]
verify_jwt = false

[functions.generate-feature-images]
verify_jwt = false
