
export const getQuestions = (language: string): string[] => {
  if (language === 'en') {
    return [
      "What name will you give this anger stack?",
      "Which CORE 4 domain are you stacking?",
      "Who/What are you stacking?",
      `At this moment, why did they make you feel anger?`,
      `At this moment, if you could yell at them, what would you say?`,
      `At this moment, if you could force them to think, say, or do anything, what would it be?`,
      `At this moment, without filter or constraints, what do you truly think about them?`,
      `At this moment, what is the thing you never want to experience again with them?`,
      `What are the non-emotional facts about the situation with them that made you feel anger?`,
      `What is the story you're telling yourself, created by this trigger, about them?`,
      "Describe in a single word the feelings that arise for you when you tell yourself that story?",
      "Describe the specific thoughts and actions that arise for you when you tell yourself this story?",
      "What evidence do you have that supports this story as absolutely true?",
      `Is the story: you described True?`,
      `Are you 100% sure that the story you described is True?`,
      "What might be possible for you in this situation if this story were false?",
      `Regardless of your anger trigger related to them and the original story you described, what do you truly want for yourself in and beyond this situation?`,
      `What do you want for them in and beyond this situation?`,
      `What do you want for them and for YOURSELF in and beyond this situation?`,
      "If you continue to tell yourself this original story, will it ultimately give you what you want?",
      "Are you ready to let go of the original story and expand your mind and reality around this trigger as you walk the path?",
      `Letting go of the original story: you described and choosing to make it specifically about you, what is MY VERSION of the story?`,
      "What evidence can you find to demonstrate that this story is true and to open your mind even more?",
      "Will this story about yourself give you what you want?",
      "What is the OPPOSITE VERSION of the story?",
      "What evidence can you find to demonstrate that this opposite version of the story is true and to open your mind even more?",
      "Will this opposite story give you what you want?",
      "What is the DESIRED VERSION of the story?",
      "What evidence can you find to demonstrate that this desired version of the story is accurate, so that you can arm yourself to move forward today?",
      "Will this desired story give you what you want?",
      "Was this anger trigger extremely positive?",
      "What is the unique life lesson you're taking from this experience?",
      "How does this lesson apply to your BODY domain?",
      "How does this lesson apply to your SPIRITUALITY domain?",
      "How does this lesson apply to your RELATIONSHIPS domain?",
      "How does this lesson apply to your BUSINESS domain?",
      "What is the most significant revelation or insight you're taking away from this Mega Stack experience and why do you feel that way?",
      "What single words would you use to describe how you feel now, at the end?",
      "What immediate actions are you determined to take now, after completing this experience?",
      "Do you want to add to the HIT list?",
      "Are there any other actions you feel determined to take?"
    ];
  } else {
    return [
      "Ce nume vei da acestui morman de furie?",
      "Ce domeniu din CORE 4 stivuiești?",
      "Pe cine/Ce stivuiești?",
      "În acest moment, de ce te-a făcut {peCinece} să simți furie?",
      "În acest moment, dacă ai putea să țipi la {peCinece} ce i-ai spune?",
      "În acest moment, dacă ai putea să-l forțezi pe {peCinece} să gândească, să spună sau să facă orice, ce ar fi?",
      "În acest moment, fără filtru sau constrângeri, ce crezi cu adevărat despre {peCinece}?",
      "În acest moment, ce este ceea ce nu vrei să experimentezi niciodată din nou cu {peCinece}?",
      "Care sunt faptele non-emoționale despre situația cu {peCinece} care te-au făcut să simți furie?",
      "Care este povestea pe care ți-o spui, creată de acest declanșator, despre {peCinece}?",
      "Descrie într-un singur cuvânt sentimentele care apar pentru tine atunci când îți spui acea poveste?",
      "Descrie gândurile și acțiunile specifice care apar pentru tine atunci când îți spui această poveste?",
      "Ce dovezi ai care susțin că această poveste este absolut adevărată?",
      "Este povestea: {careEste} Adevărată?",
      "Ești 100% sigur că povestea {careEste} este Adevărată?",
      "Ce ar putea fi posibil pentru tine în această situație dacă această poveste ar fi falsă?",
      "Indiferent de declanșatorul tău de furie legat de {peCinece} și povestea originală {careEste}, ce îți dorești cu adevărat pentru tine în și dincolo de această situație?",
      "Ce îți dorești pentru {peCinece} în și dincolo de această situație?",
      "Ce îți dorești pentru {peCinece} și pentru TINE în și dincolo de această situație?",
      "Dacă continui să-ți spui această poveste originală, îți va oferi în cele din urmă ceea ce îți dorești?",
      "Ești gata să renunți la povestea originală și să-ți extinzi mintea și realitatea în jurul acestui declanșator în timp ce parcurgi drumul?",
      "Renunțând la povestea originală: {careEste} și alegând să o faci să fie în mod specific despre tine, care este VERSIUNEA MEA a poveștii?",
      "Ce dovezi poți găsi pentru a demonstra că această poveste este adevărată și pentru a-ți deschide mintea și mai mult?",
      "Îți va oferi această poveste despre tine ceea ce îți dorești?",
      "Care este VERSIUNEA OPUSĂ a poveștii?",
      "Ce dovezi poți găsi pentru a demonstra că această versiune opusă a poveștii este adevărată și pentru a-ți deschide mintea și mai mult?",
      "Îți va oferi această poveste opusă ceea ce îți dorești?",
      "Care este VERSIUNEA DORITĂ a poveștii?",
      "Ce dovezi poți găsi pentru a demonstra că această versiune dorită a poveștii este exactă, astfel încât să te poți înarma pentru a merge mai departe astăzi?",
      "Îți va oferi această poveste dorită ceea ce îți dorești?",
      "A fost acest declanșator de furie extrem de pozitiv?",
      "Care este lecția unică de viață pe care o iei din această experiență?",
      "Cum se aplică această lecție în domeniul CORPULUI tău?",
      "Cum se aplică această lecție în domeniul SPIRITUALITĂȚII tale?",
      "Cum se aplică această lecție în domeniul RELAȚIILOR tale?",
      "Cum se aplică această lecție în domeniul AFACERII tale?",
      "Care este cea mai semnificativă revelație sau cel mai important insight cu care pleci din această experiență de Mega Stack și de ce simți așa?",
      "Ce cuvinte singulare ai folosi pentru a descrie cum te simți acum, la final?",
      "Ce acțiuni imediate ești hotărât să întreprinzi acum, după ce ai finalizat această experiență?",
      "Vrei sa adaugi la HIT list?",
      "Există și alte acțiuni pe care simți că ești hotărât să le întreprinzi?"
    ];
  }
};
