import jsPDF from 'jspdf';
import { WeeklyPlanningData } from './weeklyPlanningService';

export const exportWeeklyPlanToPDF = async (plan: WeeklyPlanningData) => {
  const doc = new jsPDF();
  
  // Set fonts
  doc.setFont('helvetica', 'bold');
  
  // Title
  doc.setFontSize(22);
  doc.setTextColor(59, 130, 246); // Blue
  doc.text('Plan Săptămânal', 105, 20, { align: 'center' });
  
  // Week info
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Săptămâna: ${plan.weekKey}`, 105, 30, { align: 'center' });
  
  // Domino Door Section
  doc.setFontSize(16);
  doc.setTextColor(139, 92, 246); // Purple
  doc.text('🎯 Domino Door', 20, 45);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  const dominoText = doc.splitTextToSize(plan.dominoTitle, 170);
  doc.text(dominoText, 20, 55);
  
  let yPos = 55 + (dominoText.length * 7) + 10;
  
  if (plan.weekGoal) {
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.setFont('helvetica', 'italic');
    const goalText = doc.splitTextToSize(plan.weekGoal, 170);
    doc.text(goalText, 20, yPos);
    yPos += goalText.length * 5 + 10;
  }
  
  // Key Points Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(34, 197, 94); // Green
  doc.text('🔑 Cele 4 Chei Măsurabile', 20, yPos);
  yPos += 10;
  
  plan.keyPoints.forEach((kp, index) => {
    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    // Key Point Number
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(`${index + 1}. ${kp.title}`, 20, yPos);
    yPos += 8;
    
    // Objective
    if (kp.objective) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 100, 100);
      doc.text('Obiectiv:', 25, yPos);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50, 50, 50);
      const objText = doc.splitTextToSize(kp.objective, 160);
      doc.text(objText, 25, yPos + 5);
      yPos += objText.length * 5 + 8;
    }
    
    // Why
    if (kp.why) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 100, 100);
      doc.text('De ce?:', 25, yPos);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50, 50, 50);
      const whyText = doc.splitTextToSize(kp.why, 160);
      doc.text(whyText, 25, yPos + 5);
      yPos += whyText.length * 5 + 8;
    }
    
    // Positive Impact
    if (kp.positiveImpact) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(34, 197, 94); // Green
      doc.text('✓ Impact Pozitiv:', 25, yPos);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(21, 128, 61);
      const posText = doc.splitTextToSize(kp.positiveImpact, 160);
      doc.text(posText, 25, yPos + 5);
      yPos += posText.length * 5 + 8;
    }
    
    // Negative Impact
    if (kp.negativeImpact) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(239, 68, 68); // Red
      doc.text('✗ Impact Negativ:', 25, yPos);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(220, 38, 38);
      const negText = doc.splitTextToSize(kp.negativeImpact, 160);
      doc.text(negText, 25, yPos + 5);
      yPos += negText.length * 5 + 8;
    }
    
    // Steps
    if (kp.steps && kp.steps.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 100, 100);
      doc.text('Pași:', 25, yPos);
      yPos += 5;
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50, 50, 50);
      kp.steps.forEach((step, sIdx) => {
        if (yPos > 280) {
          doc.addPage();
          yPos = 20;
        }
        const stepText = doc.splitTextToSize(`${sIdx + 1}. ${step}`, 155);
        doc.text(stepText, 30, yPos);
        yPos += stepText.length * 5 + 3;
      });
      yPos += 5;
    }
    
    // Responsible & Deadline
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    
    if (kp.responsible) {
      doc.text(`👤 Responsabil: ${kp.responsible}`, 25, yPos);
      yPos += 5;
    }
    
    if (kp.deadline) {
      doc.text(`📅 Deadline: ${kp.deadline}`, 25, yPos);
      yPos += 5;
    }
    
    yPos += 10; // Space before next key point
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Pagina ${i} din ${pageCount} - Generated by DOOR Planning`,
      105,
      290,
      { align: 'center' }
    );
  }
  
  // Save PDF
  doc.save(`Plan-Saptamanal-${plan.weekKey}.pdf`);
};
