/// <reference types="npm:@types/react@18.3.1" />
import * as React from 'npm:react@18.3.1'
import { Body, Container, Head, Heading, Html, Preview, Section, Text, Button, Hr } from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

interface Props {
  warriorName?: string
  warriorType?: string
  tagline?: string
  description?: string
  strengths?: string
  challenges?: string
  routineFocus?: string
  activeSteps?: string[]
  meditationMinutes?: number
  workoutDays?: number
  readingPages?: number
  checkoutUrl?: string
  language?: 'ro' | 'en'
}

const t = (lang: 'ro' | 'en') => ({
  preview: lang === 'en' ? 'Your Warrior type + full personalized routine' : 'Tipul tău de Warrior + rutina completă personalizată',
  greeting: lang === 'en' ? 'Here is your report' : 'Iată raportul tău',
  youAre: lang === 'en' ? 'You are' : 'Ești',
  strengths: lang === 'en' ? 'STRENGTHS' : 'PUNCTE FORTE',
  challenges: lang === 'en' ? 'CHALLENGES' : 'PROVOCĂRI',
  focus: lang === 'en' ? 'ROUTINE FOCUS' : 'FOCUS RUTINĂ',
  yourRoutine: lang === 'en' ? 'Your personalized routine' : 'Rutina ta personalizată',
  stepsIncluded: lang === 'en' ? 'steps included' : 'pași incluși',
  meditation: lang === 'en' ? 'Meditation' : 'Meditație',
  workout: lang === 'en' ? 'Workout' : 'Antrenament',
  reading: lang === 'en' ? 'Reading' : 'Citit',
  perWeek: lang === 'en' ? '×/week' : '×/săpt',
  perDay: lang === 'en' ? 'pages/day' : 'pag/zi',
  min: 'min',
  ctaHeader: lang === 'en' ? 'Ready to activate your Warrior routine?' : 'Gata să-ți activezi rutina Warrior?',
  ctaSub: lang === 'en' ? '7 days free trial · Then €7/month · Cancel anytime' : '7 zile trial gratuit · Apoi 7€/lună · Anulezi oricând',
  cta: lang === 'en' ? 'Activate my routine — 7-day trial' : 'Activează-mi rutina — 7 zile trial',
  footer: lang === 'en' ? 'Report generated by CEO Mind OS · Warrior Type Quiz' : 'Raport generat de CEO Mind OS · Quiz Tip Warrior',
})

const Email = ({
  warriorName = 'Warrior',
  warriorType = 'warrior',
  tagline = '',
  description = '',
  strengths = '',
  challenges = '',
  routineFocus = '',
  activeSteps = [],
  meditationMinutes = 10,
  workoutDays = 4,
  readingPages = 10,
  checkoutUrl = '#',
  language = 'ro',
}: Props) => {
  const tt = t(language)
  return (
    <Html lang={language} dir="ltr">
      <Head />
      <Preview>{tt.preview}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={heroSection}>
            <Text style={eyebrow}>⚔️ CEO MIND OS · WARRIOR REPORT</Text>
            <Heading style={h1}>
              {tt.youAre} <span style={accent}>{warriorName}</span>
            </Heading>
            <Text style={taglineStyle}>{tagline}</Text>
          </Section>

          <Section style={card}>
            <Text style={paragraph}>{description}</Text>
          </Section>

          <Section style={twoCol}>
            <div style={colBox}>
              <Text style={colLabel}>✅ {tt.strengths}</Text>
              <Text style={colText}>{strengths}</Text>
            </div>
            <div style={colBox}>
              <Text style={colLabel}>⚠️ {tt.challenges}</Text>
              <Text style={colText}>{challenges}</Text>
            </div>
          </Section>

          <Section style={{ ...card, borderColor: '#D4A84A' }}>
            <Text style={colLabel}>🎯 {tt.focus}</Text>
            <Text style={colText}>{routineFocus}</Text>
          </Section>

          <Hr style={hr} />

          <Section>
            <Heading as="h2" style={h2}>
              {tt.yourRoutine} ({activeSteps.length} {tt.stepsIncluded})
            </Heading>
            <Section style={stepsGrid}>
              {activeSteps.map((step) => (
                <Text key={step} style={stepItem}>
                  · {step.replace(/([A-Z])/g, ' $1').toLowerCase()}
                </Text>
              ))}
            </Section>
            <Section style={statsRow}>
              <Text style={statBox}>
                <strong>{tt.meditation}</strong><br />{meditationMinutes} {tt.min}
              </Text>
              <Text style={statBox}>
                <strong>{tt.workout}</strong><br />{workoutDays}{tt.perWeek}
              </Text>
              <Text style={statBox}>
                <strong>{tt.reading}</strong><br />{readingPages} {tt.perDay}
              </Text>
            </Section>
          </Section>

          <Hr style={hr} />

          <Section style={ctaSection}>
            <Heading as="h2" style={h2}>{tt.ctaHeader}</Heading>
            <Text style={ctaSub}>{tt.ctaSub}</Text>
            <Button href={checkoutUrl} style={ctaButton}>
              {tt.cta} →
            </Button>
          </Section>

          <Hr style={hr} />
          <Text style={footer}>{tt.footer}</Text>
        </Container>
      </Body>
    </Html>
  )
}

export const template = {
  component: Email,
  subject: (data: Record<string, any>) =>
    data.language === 'en'
      ? `⚔️ You are ${data.warriorName || 'Warrior'} — your full routine inside`
      : `⚔️ Ești ${data.warriorName || 'Warrior'} — rutina ta completă în interior`,
  displayName: 'Warrior Type Report',
  previewData: {
    warriorName: 'Disciplined',
    warriorType: 'disciplined',
    tagline: 'Executantul aliniat',
    description: 'Ai deja o rutină clară.',
    strengths: 'Consecvență.',
    challenges: 'Rigiditate.',
    routineFocus: 'Adâncire.',
    activeSteps: ['hydration', 'meditation', 'exercise'],
    meditationMinutes: 10,
    workoutDays: 4,
    readingPages: 10,
    checkoutUrl: 'https://example.com',
    language: 'ro',
  },
} satisfies TemplateEntry

const main: React.CSSProperties = { backgroundColor: '#ffffff', fontFamily: 'Arial, sans-serif', margin: 0, padding: 0 }
const container: React.CSSProperties = { maxWidth: '600px', margin: '0 auto', padding: '32px 24px' }
const heroSection: React.CSSProperties = { textAlign: 'center', padding: '24px 0' }
const eyebrow: React.CSSProperties = { color: '#D4A84A', fontSize: '11px', letterSpacing: '2px', fontWeight: 700, margin: 0 }
const h1: React.CSSProperties = { color: '#0B1733', fontSize: '32px', fontWeight: 800, margin: '12px 0 8px', lineHeight: 1.2 }
const accent: React.CSSProperties = { color: '#D4A84A' }
const taglineStyle: React.CSSProperties = { color: '#4a5568', fontSize: '16px', margin: 0 }
const card: React.CSSProperties = { backgroundColor: '#f7f9fc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '20px', margin: '16px 0' }
const paragraph: React.CSSProperties = { color: '#2d3748', fontSize: '15px', lineHeight: 1.6, margin: 0 }
const twoCol: React.CSSProperties = { display: 'block', margin: '16px 0' }
const colBox: React.CSSProperties = { backgroundColor: '#f7f9fc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '16px', marginBottom: '12px' }
const colLabel: React.CSSProperties = { color: '#0B1733', fontSize: '11px', letterSpacing: '1.5px', fontWeight: 700, margin: '0 0 6px' }
const colText: React.CSSProperties = { color: '#4a5568', fontSize: '14px', lineHeight: 1.5, margin: 0 }
const h2: React.CSSProperties = { color: '#0B1733', fontSize: '20px', fontWeight: 700, margin: '16px 0 8px' }
const stepsGrid: React.CSSProperties = { padding: '8px 0' }
const stepItem: React.CSSProperties = { color: '#2d3748', fontSize: '14px', margin: '4px 0', textTransform: 'capitalize' }
const statsRow: React.CSSProperties = { display: 'block', textAlign: 'center', margin: '16px 0' }
const statBox: React.CSSProperties = { display: 'inline-block', minWidth: '150px', padding: '12px', color: '#2d3748', fontSize: '13px', textAlign: 'center' }
const ctaSection: React.CSSProperties = { textAlign: 'center', padding: '24px 0' }
const ctaSub: React.CSSProperties = { color: '#4a5568', fontSize: '14px', margin: '4px 0 20px' }
const ctaButton: React.CSSProperties = { backgroundColor: '#D4A84A', color: '#0B1733', padding: '16px 32px', borderRadius: '8px', textDecoration: 'none', fontWeight: 700, fontSize: '16px', display: 'inline-block' }
const hr: React.CSSProperties = { borderColor: '#e2e8f0', margin: '24px 0' }
const footer: React.CSSProperties = { color: '#718096', fontSize: '12px', textAlign: 'center', margin: 0 }
