
import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';

type Language = 'en' | 'ro';

type Translations = {
  [key: string]: {
    [key: string]: string;
  };
};

// All translations for the app
const translations: Translations = {
  en: {
    // Brand
    "appName": "CEO Mind OS",
    "appTagline": "The Founder Operating System",
    "appDescription": "The AI-powered Operating System for founders who refuse to choose between success and life",
    
    // Auth page
    "becomeTheWarrior": "Become the Warrior",
    "youWereMeantToBe": "you were meant to be",
    "transformYourLife": "Transform your life with purpose and discipline. Our platform helps you build habits, track progress, and connect with like-minded warriors.",
    "dailyStackSystem": "Daily Stack System",
    "buildPowerfulHabits": "Build powerful habits through daily reflection and action",
    "warriorTribe": "Warrior Tribe",
    "connectWithWarriors": "Connect with warriors who challenge and support your growth",
    "growthTracking": "Growth Tracking",
    "visualizeYourProgress": "Visualize your progress with powerful analytics",
    
    // Transformation Workshop
    "transformationWorkshop": "Introspection",
    "coachingDescription": "Take a moment to reflect and get guidance through our AI coaching system",
    "prayerStackTitle": "What are you going to title this conversation with God?",
    "whatAreYouGoingToTitleThisCoaching": "What are you going to title this coaching session?",
    "whoOrWhatAreYouStacking": "Who or what are you focusing on?",
    "whyHasThisTriggeredYou": "In this moment, why has this triggered you to pray?",
    "whatIsTheStory": "What is the story you're telling yourself, created by your trigger \"this trigger\", about this situation?",
    "describeSingleWordFeelings": "Describe the single word feelings that arise for you when you tell yourself that story?",
    "iWantGodToKnow": "Lord, I want to know",
    "dearGod": "Dear GOD,",
    "singularLesson": "What is the singular lesson on life you are taking from this coaching session?",
    "significantRevelation": "What is the most significant revelation or insight you are leaving this coaching session with, and why do you feel that way?",
    "immediateActions": "What immediate actions are you committed to taking leaving this session?",
    
    // Common
    "language": "Language",
    "english": "English",
    "romanian": "Romanian",
    
    // Common UI elements
    "dashboard": "DASHBOARD",
    "stack": "INTROSPECTION",
    "triggers": "Triggers",
    "selectTrigger": "Select a trigger",
    "newStack": "New Session",
    "startStack": "Start a Session",
    "startStackDesc": "Select a trigger from the left to begin your daily reflection. This practice helps you process your emotions and experiences.",
    "power": "POWER",
    "production": "PRODUCTION",
    "stackCompleted": "Session Completed",
    "reflectionSaved": "Your reflection has been saved",
    "startNewStack": "Start New Session",
    "typeResponse": "Type your response...",
    "stackHistory": "Session History",
    "noStackHistory": "No session history yet",
    "completed": "Completed",
    "today": "Today",
    "yesterday": "Yesterday",
    
    // Trigger responses
    "reflectExperience": "Let's reflect on your experience.",
    "thankYouReflection": "Thank you for your reflection. Your insights have been saved to your COACHING.",
    
    // Button actions
    "view": "VIEW",
    "send": "Send",
    
    // Admin panel
    "toolsManagement": "Tools Management",
    "addNewTool": "Add New Tool",
    "searchTools": "Search tools...",
    "isActive": "Active",
    "inactive": "Inactive",
    "deactivate": "Deactivate",
    "activate": "Activate",
    "launchTool": "Launch Tool",
    "launching": "Launching",
    "noToolsFound": "No tools found",
    "tryAdjusting": "Try adjusting your search or filters.",
    
    // Core navigation
    "goToDashboard": "Go to Dashboard",
    "continue": "Continue",
    "backToDashboard": "Back to Dashboard",
    "core": "CORE",
    
    // Core 4 activities
    "fitness": "FITNESS",
    "fuel": "FUEL",
    "meditation": "MEDITATION",
    "memoirs": "MEMOIRS",
    "person1": "PERSON 1",
    "person2": "PERSON 2",
    "discover": "DISCOVER",
    "declare": "DECLARE",
    "thisWeek": "THIS WEEK",
    "body": "BODY",
    "being": "BEING",
    "balance": "BALANCE",
    "business": "BUSINESS",
    "share": "SHARE",
    "activityCompleted": "{activity} completed!",
    "activityIncomplete": "{activity} marked incomplete",
    "greatJob": "Great job! Your Core 4 progress has been updated.",
    "progressUpdated": "Your progress has been updated.",
    
    // Dashboard specific
    "trackActivities": "Track Activities",
    "myDaily": "MY DAILY",
    "myWeekly": "MY WEEKLY",
    "myQuarterly": "MY QUARTERLY",
    "theMemory": "THE MEMORY",
    "theScore": "THE SCORE",
    "theStreaks": "THE STREAKS",
    "theTotal": "THE TOTAL",
    "door": "DOOR",
    "game": "GAME",
    "myMissions": "MY MISSIONS",
    "warriorBody": "Warrior Body",
    "meditationWarrior": "Meditation Warrior",
    "soulmateFamily": "Soul mate Family",
    "buildingKingdom": "Building the Kingdom",
    "noStackCompletedYet": "You haven't completed your daily stack yet.",
    "beginNow": "Begin now",
    "gratefulMessage": "I'm grateful for this new opportunity to grow.",
    "noDoorTasksYet": "You haven't set Domino Door tasks yet.",
    "noTaskSet": "No task set",
    "setTasks": "Set Tasks",
    "viewCoreDetails": "View Core Details",
    
    // Door specific translations
    "commandCenter": "TO DO",
    "doorTitle": "DOOR",
    "doorPlanningSystem": "Weekly Planning System",
    "currentWeek": "Current Week",
    "pastWeek": "Past Week", 
    "futureWeek": "Future Week",
    "viewingPastWeek": "You are viewing a past week",
    "viewingFutureWeek": "You are viewing a future week",
    "backToCurrentWeek": "🏠 Back to Current Week",
    "ideaList": "IDEA LIST",
    "hotList": "HOT LIST", 
    "weeklyGoal": "WEEKLY GOAL",
    "dominoDoor": "DOMINO DOOR",
    "weeklyMassiveGoal": "WEEKLY MASSIVE GOAL",
    "tasks": "TASKS",
    "todoList": "TO DO LIST",
    "doList": "DO LIST",
    "monday": "Monday",
    "tuesday": "Tuesday", 
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "mondayShort": "Mon",
    "tuesdayShort": "Tue",
    "wednesdayShort": "Wed", 
    "thursdayShort": "Thu",
    "fridayShort": "Fri",
    "saturdayShort": "Sat",
    "sundayShort": "Sun",
    "noGoalSelected": "No goal selected yet",
    "dragGoalToSet": "Drag an item from the idea list to set your weekly massive goal",
    "mainGoal": "Main Goal:",
    "keyPoints": "Key Points:",
    "keyPoint": "Key point",
    "noTasksForDay": "No tasks for this day",
    "noDoItemsForDay": "No DO items for this day",
    "dragItemsHere": "Drag items here from your IDEA list",
    "yourIdeaListEmpty": "Your idea list is empty",
    "addNewItemsToStart": "Add new items to get started",
    "addNewIdea": "Add New Idea",
    "addItem": "Add Item",
    "searchItems": "Search items...",
    "searchIdeas": "Search ideas...",
    "normal": "Normal",
    "important": "Important",
    "urgent": "Urgent",
    "urgentImportant": "Urgent & Important",
    "moveBackToIdeaList": "Move back to Idea List",
    "moveBackToHotList": "Move back to Hot List",
    "keyPointLabel": "Key Point",
    "todayLabel": "Today",
    "weekLabel": "Week",
    "autoSaveInfo": "Your weekly planning is saved automatically",
    "enterNewIdea": "Enter your new idea...",
    "selectPriority": "Select priority",
    "deleteIdea": "Delete idea",
    "editIdea": "Edit idea",
    "weekly": "Weekly",
    "planning": "Planning",
    
    // Fact Maps
    "backToFactMaps": "Back to Fact Maps",
    "mapOrGoalNotFound": "Map or goal not found",
    "enterYourAnswer": "Enter your answer here...",
    "characters": "Characters",
    "previous": "Previous",
    "next": "Next",
    "reset": "Reset",
    "save": "Save",
    "success": "Success",
    "answersSaved": "Your answers have been saved.",
    "stackShared": "Stack Shared",
    "linkCopiedToClipboard": "Link copied to clipboard",
    "savedToLibrary": "Saved to Library",
    "savedToLibraryDesc": "Your stack has been saved to your library",
    "stackLibrary": "Stack Library",
    "all": "All",
    "shared": "Shared",
    "noStacksInLibrary": "You don't have any stacks in your library yet",
    "createYourFirstStack": "Create Your First Stack",
    "errorSaving": "Error Saving",
    "startOver": "Start Over",
    "actionDescription": "Action description",
    "addAction": "Add Action",
    "actionAdded": "Action Added",
    "actionAddedDesc": "Your action has been added successfully",
    "reminderSet": "Reminder Set",
    "reminderSetDesc": "You will be reminded about this action",
    "actions": "Actions",
    "coaching_completed": "Coaching Completed",
    "coaching_completed_desc": "Your coaching session has been saved",
    "startNew": "Start New",
    "noCoachingHistoryYet": "No coaching history yet",
    
    // Divine Coaching specific
    "whatAreYouGoingToTitleThisDivineCoaching": "What are you going to title this Divine coaching session?",
    "whoOrWhatAreYouStackingDivine": "Who or what are you stacking?",
    "whyHasThisTriggeredYouToPray": "In this moment, why has this triggered you to pray?",
    "whatIsTheStoryDivineTrigger": "What is the story you're telling yourself, created by this trigger, about this and the situation?",
    "describeSingleWordFeelingsDivine": "Describe the single word feelings that arise for you when you tell yourself that story?",
    "godIsListening": "God is listening what do you have to say?",
    "iWantGODToKnow1": "Lord, I want to know:",
    "iWantGODToKnow2": "Lord, I want to know:",
    "iWantGODToKnow3": "Lord, I want to know:",
    "iWantGODToKnow4": "Lord, I want to know:",
    "dearGODWhatDoYouWantMeToSee": "Dear GOD, What do you want me to see here?",
    "whatDoYouWantMeToHear": "What do you want me to hear?",
    "whatDoYouWantMeToLearn": "What do you want me to learn?",
    "whatDoYouWantMeToFeel": "What do you want me to feel?",
    "whatDoYouWantMeToKnow": "What do you want me to know?",
    "whatDoYouWantMeToDo": "What do you want me to do?",
    "godHeardYou": "God wants you to:",
    "singularLessonDivine": "What is the singular lesson on life you are taking from this Divine coaching session?",
    "howDoesThisLessonApplyToBody": "How does this lesson apply to your Body?",
    "howDoesThisLessonApplyToBeing": "How does this lesson apply to your Being?",
    "howDoesThisLessonApplyToBalance": "How does this lesson apply to your Balance?",
    "howDoesThisLessonApplyToBusiness": "How does this lesson apply to your Business?",
    "significantRevelationDivine": "What is the most significant revelation or insight you are leaving this Divine coaching session with, and why do you feel that way?",
    "immediateActionsDivine": "What immediate actions are you committed to taking leaving this session?",
    "doYouWantToAddToHotList": "Do you want to add this to hot list?",
    "isThereAnythingElseToAddToHotList": "Is there anything else you want to add to hot list?",
    
    // Landing Page - CEO Mind OS
    "jumpToFreedom": "CEO Mind OS",
    "haveItAll": "Have It All",
    "startNowSeeResults": "Start Now. See Results in 48 Hours.",
    "freeTrial7Days": "Free 7-day trial (card required). Zero risk. Cancel anytime during trial with no charge.",
    "fifteenMinuteSetup": "15-Minute Setup",
    "quickOnboarding": "Quick onboarding, then execute",
    "resultsIn48h": "Results in 48h",
    "clarityFirstWins": "Clarity + first wins",
    "zeroRiskGuarantee": "Zero Risk Guarantee",
    "sevenDayTrialCancelFree": "7-day trial, cancel free",
    "startYour7DayFreeTrial": "Start Your 7-Day Free Trial",
    "membersTransformed": "500+ members transformed",
    "averageLifeSatisfaction": "Average +35% life satisfaction in 30 days",
    "costOfWaiting": "The Cost of Waiting",
    "everyDayWithoutSystem": "Every Day Without a System Costs You",
    "whileYouHesitate": "While you hesitate, life keeps moving. Here's what you lose with each passing day:",
    "bodyEnergyCost": "-0.5% energy & vitality",
    "beingPeaceCost": "-1 moment of inner peace",
    "balanceConnectionCost": "-1 meaningful connection",
    "businessRevenueCost": "-$50-500 potential revenue",
    "thirtyDaysFromNow": "30 Days From Now",
    "transformationChoice": "You can either be 30 days into your transformation, experiencing more energy, clarity, better relationships, and growing income... or still wondering 'what if?'",
    "energyLevel": "Energy Level",
    "mindfulMinutes": "Mindful Minutes",
    "qualityMoments": "Quality Moments",
    "productivityIncrease": "Productivity",
    "startMyTransformationToday": "Start My Transformation Today",
    "averageSetupTime": "Average setup time: 15 minutes",
    "aboutJumpToFreedom": "About CEO Mind OS",
    "ourMissionValues": "Our Mission & Values",
    "aboutDescription": "Learn about CEO Mind OS's mission to help you achieve holistic success across Body, Being, Balance, and Business through proven systems and daily habits.",
    "missionToHelpYou": "We're on a mission to help you break free from the trap of imbalance and build a life where you truly have it all - health, peace, love, and prosperity.",
    "storyBehind": "The Story Behind CEO Mind OS",
    "purposeDriven": "Purpose-Driven",
    "purposeDrivenDesc": "Every feature is designed to help you live with intention and achieve meaningful goals across all areas of life.",
    "holisticGrowth": "Holistic Growth",
    "holisticGrowthDesc": "We believe true success comes from balance - nurturing your body, mind, relationships, and career together.",
    "continuousImprovement": "Continuous Improvement",
    "continuousImprovementDesc": "Small daily actions compound into extraordinary results. We help you build systems, not just motivation.",
    "communitySupport": "Community Support",
    "communitySupportDesc": "You're not alone on this journey. Connect with like-minded individuals committed to growth.",
    "fourPillarsOfFreedom": "The 4 Pillars of Freedom",
    "trueFreedomComes": "True freedom comes from mastery in all four areas of life. Neglect one, and the others eventually suffer.",
    "bodyPillarDesc": "Physical health, energy, fitness, and vitality",
    "beingPillarDesc": "Mental clarity, spirituality, and inner peace",
    "balancePillarDesc": "Relationships, family, and meaningful connections",
    "businessPillarDesc": "Career growth, finances, and professional success",
    "ourMission": "Our Mission",
    "missionStatement": "To empower 1 million people to break free from the trap of imbalanced living and build lives of holistic abundance.",
    "ourVision": "Our Vision",
    "visionStatement": "A world where success is measured not by achievements in isolation, but by the harmony and fulfillment across all dimensions of life.",
    "ourCoreValues": "Our Core Values",
    "coreValuesPrinciples": "These principles guide everything we build and every decision we make.",
    "readyToJump": "Ready to Start CEO Mind OS?",
    "joinThousands": "Join thousands of people who have transformed their lives by mastering all four pillars. Start your 7-day free trial today.",
    "startFreeTrial": "Start Free Trial",
    "learnMore": "Learn More",
    
    // XP System translations
    "level": "Level",
    "xp": "XP",
    "xpToNextLevel": "XP to next level",
    "totalXP": "Total XP",
    "levelUp": "Level Up!",
    "levelUpCongrats": "Congratulations!",
    "youReachedLevel": "You've reached level",
    "keepGoing": "Keep going! Great things await.",
    "continueJourney": "Continue Journey",
    "xpEarned": "XP earned",
    
    // Level titles
    "levelTitle_1": "Awakening Seeker",
    "levelTitle_2": "Focused Initiate",
    "levelTitle_3": "Disciplined Warrior",
    "levelTitle_4": "Rising Champion",
    "levelTitle_5": "Enlightened Master",
    "levelTitle_6": "Wise Sage",
    "levelTitle_7": "Legendary Hero",
    "levelTitle_8": "Transcendent Being",
    "levelTitle_9": "Cosmic Warrior",
    "levelTitle_10": "Infinite Master",
    
    // Daily Challenges
    "dailyChallenges": "Daily Challenges",
    "challengeProgress": "Progress",
    "claimReward": "Claim Reward",
    "challengeCompleted": "Completed!",
    "challengesRefreshIn": "Challenges refresh in",
    "allChallengesComplete": "All challenges complete! Great work!",
    "hours": "hours",
    "minutes": "minutes",
    
    // Challenge types
    "challenge_complete_stack": "Complete a Stack",
    "challenge_complete_stack_desc": "Finish a reflection stack",
    "challenge_read_pages": "Read Pages",
    "challenge_read_pages_desc": "Read at least 5 pages today",
    "challenge_complete_core": "Complete Core 4",
    "challenge_complete_core_desc": "Complete all Core 4 activities",
    "challenge_complete_actions": "Complete Actions",
    "challenge_complete_actions_desc": "Complete 3 action items",
    "challenge_login_streak": "Login Streak",
    "challenge_login_streak_desc": "Maintain your streak",
    "challenge_complete_door": "Door Tasks",
    "challenge_complete_door_desc": "Complete 5 door tasks",
    
    // Smart Notifications
    "goodMorning": "Good Morning!",
    "goodAfternoon": "Good Afternoon!",
    "goodEvening": "Good Evening!",
    "streakAtRisk": "Your streak is at risk!",
    "streakAtRiskDesc": "Complete an activity to keep your streak alive",
    "almostLevelUp": "Almost there!",
    "almostLevelUpDesc": "Just {xp} XP to level up!",
    "welcomeBack": "Welcome back!",
    "welcomeBackDesc": "Ready to continue your journey?",
    "greatStreak": "Amazing streak!",
    "greatStreakDesc": "{days} days and counting!",
    "startSession": "Start Session",
    "viewProgress": "View Progress",
    
    // Streak Milestones
    "streakMilestone": "Streak Milestone!",
    "days": "days",
    "dayStreak": "Day Streak",
    "streakBonus": "Streak Bonus",
    "streakShieldUnlocked": "Streak Shield Unlocked!",
    "streakShieldDesc": "You now have protection against losing your streak",
    "keepItUp": "Keep Going!",
    
    // Streak milestone titles
    "streak_7_title": "One Week Warrior",
    "streak_7_subtitle": "7 days of dedication",
    "streak_7_message": "You've shown real commitment. The habit is forming!",
    "streak_30_title": "Monthly Master",
    "streak_30_subtitle": "30 days of discipline",
    "streak_30_message": "A full month! You're building something extraordinary.",
    "streak_100_title": "Century Champion",
    "streak_100_subtitle": "100 days of excellence",
    "streak_100_message": "100 days of growth. You're truly unstoppable!",
    "streak_365_title": "Annual Legend",
    "streak_365_subtitle": "365 days of mastery",
    "streak_365_message": "A full year! You've achieved legendary status.",
    
    // Badge Unlock
    "badgeUnlocked": "Badge Unlocked!",
    "newBadge": "New Badge",
    "awesome": "Awesome!",
    
    // Weekly Recap
    "weeklyRecap": "Weekly Recap",
    "weekNumber": "Week",
    "daysActive": "Days Active",
    "daysActiveSubtitle": "You showed up this week!",
    "stacksCompleted": "Stacks Completed",
    "stacksCompletedSubtitle": "Reflection sessions done",
    "pagesRead": "Pages Read",
    "pagesReadSubtitle": "Knowledge gained",
    "actionsCompleted": "Actions Completed",
    "actionsCompletedSubtitle": "Tasks accomplished",
    "xpEarnedWeek": "XP Earned",
    "xpEarnedSubtitle": "Experience gained",
    "currentStreakWeek": "Current Streak",
    "currentStreakSubtitle": "Days in a row",
    "badgesEarned": "Badges Earned",
    "badgesEarnedSubtitle": "Achievements unlocked",
    "greatWeek": "Great week!",
    "seeYouNextWeek": "See you next week!",
    
    // Milestone Celebrations
    "milestoneReached": "Milestone Reached!",
    "firstStack": "First Stack",
    "firstStackMessage": "You completed your first reflection stack!",
    "tenStacks": "10 Stacks",
    "tenStacksMessage": "A milestone of reflection and growth!",
    "hundredPages": "100 Pages",
    "hundredPagesMessage": "You've read 100 pages of wisdom!",
    "firstWeek": "First Week",
    "firstWeekMessage": "Your first week streak!",
    "firstMonth": "First Month",
    "firstMonthMessage": "An entire month of dedication!",
    "levelFive": "Level 5",
    "levelFiveMessage": "You've reached Level 5!",
    "levelTen": "Level 10",
    "levelTenMessage": "The big 10! You're a master!",
    
    // Rewards Showcase
    "rewards": "Rewards",
    "unlockableRewards": "Unlockable Rewards",
    "themes": "Themes",
    "avatars": "Avatars",
    "frames": "Frames",
    "unlockAt": "Unlock at Level",
    "unlocked": "Unlocked",
    "equipped": "Equipped",
    "equip": "Equip",
    "locked": "Locked",
    "nextReward": "Next Reward",
    
    // Reward names
    "reward_dark_theme": "Dark Warrior Theme",
    "reward_dark_theme_desc": "A sleek dark theme for focused warriors",
    "reward_gold_theme": "Golden Champion Theme",
    "reward_gold_theme_desc": "A prestigious golden theme",
    "reward_nature_theme": "Nature Harmony Theme",
    "reward_nature_theme_desc": "Calming nature-inspired colors",
    "reward_avatar_warrior": "Warrior Avatar",
    "reward_avatar_warrior_desc": "The classic warrior avatar",
    "reward_avatar_sage": "Sage Avatar",
    "reward_avatar_sage_desc": "Wisdom personified",
    "reward_avatar_legend": "Legend Avatar",
    "reward_avatar_legend_desc": "For legendary achievers",
    "reward_frame_bronze": "Bronze Frame",
    "reward_frame_bronze_desc": "A sturdy bronze frame",
    "reward_frame_silver": "Silver Frame",
    "reward_frame_silver_desc": "An elegant silver frame",
    "reward_frame_gold": "Gold Frame",
    "reward_frame_gold_desc": "The prestigious gold frame",
    
    // Gamification general
    "gamification": "Gamification",
    "achievements": "Achievements",
    "progress": "Progress",
    "streak": "Streak",
    "currentStreak": "Current Streak",
    "longestStreak": "Longest Streak",
    "totalDaysActive": "Total Days Active",
    "loading": "Loading...",
    "error": "Error",
    "close": "Close",
    "ok": "OK",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "delete": "Delete",
    "edit": "Edit",
    "add": "Add",
    "remove": "Remove",
    "update": "Update",
    "create": "Create",
    "submit": "Submit",
    "done": "Done",
    "finish": "Finish",
    "start": "Start",
    "stop": "Stop",
    "pause": "Pause",
    "resume": "Resume",
    "retry": "Retry",
    "back": "Back",
    "forward": "Forward",
    "yes": "Yes",
    "no": "No",
    
    // DailyCompactCard
    "dailyPage": "Daily Page",
    "read": "Read",
    "pleaseLoginToTrack": "Please login to track progress",
    "actionCompletedToast": "Action completed!",
    "showMore": "Show more",
    "showLess": "Show less",
    
    // Biz 4 translations
    "biz4": "BIZ 4",
    "dailyFour": "BIZ 4",
    "weeklyTwo": "WEEKLY TWO",
    "contentDesc": "Create 1 piece of content",
    "engageDesc": "Engage with your audience",
    "outreachDesc": "Contact new prospects",
    "closeDesc": "Sales conversation/follow-up",
    "podcastDesc": "Record your weekly episode",
    "webinarDesc": "Host your weekly webinar/live",
    
    // Menu items - CEO Mind OS Rebrand
    "aiCoaches": "AI Coaches",
    "lifeVision": "Life Vision",
    "ninetyDayChallenge": "90-Day Challenge",
    "dailyPlanner": "Daily Planner",
    "businessCoach": "Business Coach",
    "successCoach": "Success Principles",
    "mindsetCoach": "Mindset Coach",
    "lifeCoach": "Life Coach",
    "emotionCoach": "Emotion Coach",
    "gratitudeJournal": "Gratitude Journal",
    "businessTracker": "Business Tracker",
    "learningHub": "Learning Hub",
    "masteryProgram": "Mastery Program",
    "weeklyGoals": "Weekly Goals",
    "todaysFocus": "Today's Focus",
    "dailyRoutine": "Daily Routine",
    
    // Legacy menu items (kept for compatibility)
    "haveItAllBlueprint": "📖 Life Vision",
    "haveItAllChallenge": "🚀 90-Day Challenge",
    "masterPlan": "📚 Success Principles",
    "myProjects": "My Projects",
    "activeJourney": "Active Journey",
    "knowledgeBase": "Knowledge Base",
    "dailyMasterStack": "Daily Planner",
    "angerAlchemy": "Emotion Coach",
    "divineGratitude": "Mindset & Gratitude",
    "divineConnection": "Mindset Coach",
    "gratitudePractice": "Gratitude Journal",
    "principleCoaching": "Success Coach",
    "wisdomOracle": "Life Coach",
    "businessEmpire": "Business Coach",
    "mastersAcademy": "Mastery Program",
    "reflectionJournal": "Reflection Journal",
    "voiceAnalysis": "Voice Analysis",
    "transformationToolkit": "AI Coaches",
    "freedomMissions": "Freedom Missions",
    "notes": "Notes",
    "library": "Library",
    "subscriptions": "Subscriptions",
    "admin": "Admin",
    "settings": "Settings",
    "support": "Support",
    
    // DoorHeader
    "history": "History",
    "deleteBtn": "Delete",
    "cleanDuplicates": "Clean Duplicates",
    "clearWeek": "Clear Week",
    "deleteHistory": "Delete History",
    
    // Landing Page Hero - CEO Mind OS Rebrand
    "landingHeroTitle": "<span>Success Without Sacrifice.</span>",
    "landingHeroTitlePart2": "The AI-Powered Founder Operating System",
    "landingHeroDesc": "<span>CEO Mind OS</span> helps entrepreneurs grow their business <span>WITHOUT</span> losing their health, relationships, or peace of mind — transform from overwhelmed to fulfilled",
    "landingHeroTrusted": "Trusted by <span>65,000+ achievers in 40+ countries</span> • AI guidance across <span>Body, Being, Balance & Business</span> • First results in <span>48 hours</span>",
    "landingStartTrial": "Start 3-Day Trial",
    "landingSeePricing": "See Pricing & ROI",
    "landingTransformIn4Areas": "Transformation in 4 areas",
    "landingCompleteLifeSystem": "Complete life system",
    "landing3DayFreeTrial": "3-day free trial",
    "landingVideoCaption": "See how the system works in practice",
    "landingAlreadyHaveAccount": "Already have an account?",
    "landingAuthenticate": "Sign In",
    
    // Landing Page - Pit Section
    "landingPitTitle": "Are You Trapped in The Pit?",
    "landingPitSubtitle": "The Pit of Imbalance has 5 warning signs. Check what resonates with you:",
    "landingPitWorkConstantly": "I work constantly but results aren't coming",
    "landingPitWorkConsequence": "→ Guaranteed burnout in 6-12 months, business collapse",
    "landingPitDisconnected": "I feel disconnected from my family/partner",
    "landingPitDisconnectedConsequence": "→ Divorce or destroyed relationships, children who suffer",
    "landingPitBodySuffering": "My body is suffering (fatigue, weight gain, no energy)",
    "landingPitBodyConsequence": "→ Chronic disease, physical exhaustion, heart risk",
    "landingPitNumb": "I numb myself with food/alcohol/social media",
    "landingPitNumbConsequence": "→ Addictions, depression, loss of identity",
    "landingPitDeserve": "I feel like I don't deserve more",
    "landingPitDeserveConsequence": "→ Perpetual self-sabotage, never reaching your potential",
    "landingPitChecked": "You checked {count} of 5 — You're in The Pit.",
    "landingPitGoodNews": "The good news? <span>There's a way out.</span> CEO Mind OS teaches you how to escape The Pit and build real balance across Body, Being, Balance & Business.",
    "landingPitCloseToEdge": "You're close to the edge of The Pit. Now is the time to build a system that <span>protects you and puts you on the path to growth.</span>",
    "landingPitExcellent": "Excellent that you don't resonate with these symptoms! Still, CEO Mind OS teaches you <span>how to PROTECT</span> what you've built and <span>SCALE</span> without sacrificing anything.",
    
    // Landing Page - Unique Mechanism
    "landing5Pillars": "The 5 Pillars of Freedom",
    "landing5PillarsDesc": "This isn't a productivity tool. It's a <span>complete life system</span> that integrates Body, Being, Balance, and Business into one unified framework.",
    "landingBodyDesc": "Daily movement & nutrition rituals",
    "landingBodyResult": "Energy, strength, vitality",
    "landingBeingDesc": "Meditation, Stack & inner clarity",
    "landingBeingResult": "Peace, purpose, mental power",
    "landingBalanceDesc": "Adding value to relationships daily",
    "landingBalanceResult": "Deep connections, love, legacy",
    "landingBusinessDesc": "Strategic learning & application",
    "landingBusinessResult": "Growth, income, impact",
    "landingDoorTitle": "The Door",
    "landingDoorDesc": "Weekly planning & execution",
    "landingDoorResult": "Focus on what truly matters",
    "landingSystemTitle": "Works Together as ONE SYSTEM",
    "landingSystemDesc": "Each pillar connects with the others. Body gives you energy. Being gives you clarity. Balance keeps you grounded. Business drives growth. The Door keeps you focused weekly. <span>One without the others leads to imbalance.</span>",
    
    // Landing Page - Urgency Section
    "landingCostOfWaiting": "The Cost of Waiting",
    "landingEveryDayWithout": "Every Day Without a System Costs You",
    "landingWhileYouHesitate": "While you hesitate, life keeps moving. Here's what you lose with each passing day:",
    "landingBodyCost": "-0.5% energy & vitality each day you skip your health routine",
    "landingBeingCost": "-1 moment of inner peace lost to stress and mental fog",
    "landingBalanceCost": "-1 meaningful connection with loved ones you'll never get back",
    "landingBusinessCost": "-$50-500 potential revenue from missed opportunities and chaos",
    "landing30DaysFromNow": "30 Days From Now",
    "landing30DaysDesc": "You can either be 30 days into your transformation, experiencing more energy, clarity, better relationships, and growing income... or still wondering \"what if?\"",
    "landingEnergyLevel": "Energy Level",
    "landingMindfulMinutes": "Mindful Minutes",
    "landingQualityMoments": "Quality Moments",
    "landingProductivity": "Productivity",
    "landingStartTransformation": "Start My Transformation Today",
    "landingAverageSetupTime": "Average setup time: 15 minutes",
    
    // Landing Page - For Whom Section
    "landingForWhomTitle": "Is CEO Mind OS Right for You?",
    "landingForWhomSubtitle": "Be honest with yourself: if you see yourself in the left column, this is for you. If you're in the right column, it's <span>not yet</span> the right time.",
    "landingIsForYou": "CEO Mind OS IS for you if:",
    "landingNotForYou": "CEO Mind OS is NOT for you if:",
    "landingIdeal1": "You want to HAVE IT ALL — not just money, but health, relationships, and inner peace",
    "landingIdeal2": "You're willing to confront the truth about your current life",
    "landingIdeal3": "You want a structured system, not weekend motivation",
    "landingIdeal4": "You understand that real change requires time, energy, and commitment",
    "landingIdeal5": "You want to leave a legacy for your children — an example of a complete man",
    "landingNot1": "You're looking for a quick fix or magic 'hack'",
    "landingNot2": "You're not willing to do the daily work",
    "landingNot3": "You only want money, without balance in body, relationships, or spirit",
    "landingNot4": "You believe you already know everything and don't need a system",
    "landingNot5": "You're not willing to tell the truth about where you are now",
    "landingIdealSummary": "<span>In short:</span> You want a healthy body, strong relationships, spiritual clarity AND a profitable business — and you're ready to follow a complete system.",
    "landingNotSummary": "<span>In short:</span> If you only want money without balance or you're looking for shortcuts, CEO Mind OS is not for you. Come back when you're ready for complete transformation.",
    "landingForWhomFooter": "If you see yourself in the green column, start your free trial. If you're in red, save this page and come back when you're ready.",
    "landingForWhomFooterHighlight": "CEO Mind OS only works for those who are truly ready to transform.",
    
    // Landing Page - Founder Section
    "landingFounderTitle": "Why I Created CEO Mind OS",
    "landingFounderSubtitle": "The story behind the system that transforms stuck entrepreneurs into balanced leaders",
    "landingFounderName": "[Founder Name]",
    "landingFounderRole": "Founder, CEO Mind OS",
    "landingFounderYears": "<span>7 years.</span> It took me 7 years to discover, test, and prove the path to true freedom.",
    "landingFounderStory1": "In 2016, I had \"everything\": €1M+ revenue, team of 15, beautiful offices. But the reality? <span>Complete burnout, 230 lbs, chronic anxiety, a wife I saw 2 hours a week</span>.",
    "landingFounderStory2": "I ended up in the hospital after an anxiety attack. Doctors told me: <span>\"If you don't change something radically, you don't have much time left.\"</span> I was 32 years old and ready to die.",
    "landingFounderStory3": "I realized the brutal truth: <span>I had money, but I didn't have LIFE</span>. My body was collapsing. My relationship with my wife was dead. I felt nothing spiritual. Business was running, but I was a human ruin.",
    "landingFounderStory4": "I refused to accept this was the end. I started looking for answers — not in pills or weekend motivation, but in <span>brutal truth</span>. I realized the problem wasn't just in business. It was in <span>ALL areas simultaneously</span> — body, spirit, relationships, business.",
    "landingFounderResultsTitle": "The transformation results:",
    "landingFounderResult1": "Lost 65 lbs in 4 months",
    "landingFounderResult2": "From depression to mental power and clarity",
    "landingFounderResult3": "Business grew to €5M+ in 3 years",
    "landingFounderResult4": "From toxic relationship to passionate marriage",
    "landingFounderResult5": "Father and husband guided by faith",
    "landingFounderConclusion1": "<span>Success without balance is just another form of poverty.</span> You can have millions in the bank and still be in The Pit — disconnected, desensitized, destroyed inside. I was there. <span>I don't want other men to end up where I was.</span>",
    "landingFounderConclusion2": "I systematized everything I learned in those 7 years and transformed it into CEO Mind OS. Not because I want to sell something — because <span>I had no one to show me the way when I was in The Pit</span>. And I know that pain. <span>You now have the chance I never had.</span>",
    "landingFounderStats": "Now the system is used by 65,000+ men in 40+ countries. Built on timeless principles, adapted for modern life.",
    
    // Landing Page - Final CTA
    "landingFinalCTATitle": "Start Now. See Results in 48 Hours.",
    "landingFinalCTASubtitle": "Free 3-day trial (card required). Zero risk. Cancel anytime during trial with no charge.",
    "landing15MinSetup": "15-Minute Setup",
    "landingQuickOnboarding": "Quick onboarding, then execute",
    "landingResultsIn48h": "Results in 48h",
    "landingClarityFirstWins": "Clarity + first wins",
    "landingZeroRiskGuarantee": "Zero Risk Guarantee",
    "landing3DayTrialCancelFree": "3-day trial, cancel free",
    "landingStartFreeTrial": "Start Your 3-Day Free Trial",
    "landingMembersStats": "500+ members transformed • Average +35% life satisfaction in 30 days • 3-day free trial",
    "landingPlanYour2026": "Or plan your 2026 for free",
    "undoCtrl": "Undo (Ctrl+Z)",
    "redoCtrl": "Redo (Ctrl+Shift+Z)",
    
    // VoiceLanguageToggle
    "voiceRecognitionLanguage": "Voice recognition language",
    "clickToChange": "Click to change",
    
    // Index.tsx Meta tags
    "indexMetaTitle": "CEO Mind OS — Success Without Sacrifice: AI-Powered Founder Operating System",
    "indexMetaDescription": "CEO Mind OS is the AI-powered Founder Operating System that helps entrepreneurs grow their business WITHOUT losing their health, relationships, or peace of mind. Transform all 4 life areas simultaneously.",
    
    // HeroSection.tsx
    "heroSuccess": "Success",
    "heroWithout": "Without",
    "heroSacrifice": "Sacrifice",
    "heroSubtitle": "The complete AI system for entrepreneurs who want it ALL: healthy body, strong relationships, inner peace AND profitable business.",
    "heroFeature1": "4 AI Coaches (Body, Mindset, Relationships, Business)",
    "heroFeature2": "Warrior Routine - 30 min/day that changes everything",
    "heroFeature3": "The Door - Intelligent weekly planning system",
    "heroLogin": "Login",
    "heroStartFreeTrial": "Start Free Trial",
    "heroStart3DayTrial": "Start 3-Day Free Trial",
    "heroSeeHowItWorks": "See How It Works",
    "hero4LifeAreas": "4 Life Areas Integrated",
    "hero90DayGuarantee": "90-Day Guarantee",
    "heroCancelAnytime": "Cancel Anytime",
    "heroVideoCaption": "Watch: How CEO Mind OS transforms entrepreneurs in 90 days",
    "heroUsedBy": "Used by entrepreneurs in E-commerce, SaaS, Consulting, Real Estate",
    
    // ChampionRoutine STEP_LABELS
    "stepEmotionalCheck": "Emotional Check-in",
    "stepStackSelection": "Choose Stack",
    "stepEmotionalTransform": "Emotional Transform",
    "stepGratitude": "Gratitude",
    "stepHydration": "Hydration",
    "stepMeditation": "Meditation",
    "stepAutosuggestion": "Autosuggestion",
    "stepVisionDeclaration": "Vision Declaration",
    "stepExercise": "Exercise",
    "stepMealPlanning": "Meal Planning",
    "stepContentCreation": "Content Creation",
    "stepDailyTasks": "Daily Tasks",
    "stepRelationships": "Relationships",
    "stepBreathing": "Breathing",
    "stepVisualization": "Visualization",
    "stepReading": "Reading",
    "stepJournaling": "Journaling",
    "stepLightExposure": "Natural Light",
    "stepLearn": "Learn",
    "stepApply": "Apply/Teach",
    "stepHabitBody": "Habits: Body",
    "stepHabitBeing": "Habits: Being",
    "stepHabitBalance": "Habits: Balance",
    "stepHabitBusiness": "Habits: Business",
    "stepTodaysTasks": "Today's Tasks",
    "stepCompletion": "Completion",
    
    // Footer links
    "footerPricing": "Pricing",
    "footerTerms": "Terms of Service",
    "footerPrivacy": "Privacy Policy",
    "footerSupport": "Support",
    "footerLogin": "Login",
    "footerAllRightsReserved": "All rights reserved."
  },
  ro: {
    // Brand
    "appName": "CEO Mind OS",
    "appTagline": "The Founder Operating System",
    "appDescription": "Sistemul de operare pentru fondatori, alimentat de AI, pentru antreprenori care vor totul",
    
    // Auth page
    "becomeTheWarrior": "Devino Războinicul",
    "youWereMeantToBe": "care ai fost menit să fii",
    "transformYourLife": "Transformă-ți viața cu scop și disciplină. Platforma noastră te ajută să îți construiești obiceiuri, să îți urmărești progresul și să te conectezi cu războinici care gândesc la fel.",
    "dailyStackSystem": "Sistemul Zilnic Stack",
    "buildPowerfulHabits": "Construiește obiceiuri puternice prin reflecție și acțiune zilnică",
    "warriorTribe": "Tribul Războinicilor",
    "connectWithWarriors": "Conectează-te cu războinici care îți provoacă și susțin creșterea",
    "growthTracking": "Urmărirea Creșterii",
    "visualizeYourProgress": "Vizualizează-ți progresul cu analize puternice",
    
    // Transformation Workshop
    "transformationWorkshop": "Introspecție",
    "coachingDescription": "Ia-ți un moment pentru a reflecta și a primi îndrumare prin sistemul nostru de coaching cu AI",
    "prayerStackTitle": "Ce titlu vei da acestei conversații cu Dumnezeu?",
    "whatAreYouGoingToTitleThisCoaching": "Ce titlu vei da acestei sesiuni de coaching?",
    "whoOrWhatAreYouStacking": "Pe cine sau ce te concentrezi?",
    "whyHasThisTriggeredYou": "În acest moment, de ce te-a declanșat să te rogi?",
    "whatIsTheStory": "Care este povestea pe care ți-o spui, creată de declanșatorul tău \"this trigger\", despre această situație?",
    "describeSingleWordFeelings": "Descrie sentimentele într-un singur cuvânt care apar pentru tine când îți spui acea poveste?",
    "iWantGodToKnow": "Doamne, vreau să știu",
    "dearGod": "Dragă DOAMNE,",
    "singularLesson": "Care este lecția singulară despre viață pe care o iei din această sesiune de coaching?",
    "significantRevelation": "Care este cea mai semnificativă revelație sau insight cu care pleci din această sesiune de coaching și de ce te simți așa?",
    "immediateActions": "Ce acțiuni imediate te angajezi să faci când părăsești această sesiune?",
    
    // Common
    "language": "Limbă",
    "english": "Engleză",
    "romanian": "Română",
    
    // Common UI elements
    "dashboard": "PANOU DE CONTROL",
    "stack": "INTROSPECȚIE",
    "triggers": "Declanșatori",
    "selectTrigger": "Selectează un declanșator",
    "newStack": "Sesiune Nouă",
    "startStack": "Începe o Sesiune",
    "startStackDesc": "Selectează un declanșator din stânga pentru a începe reflecția zilnică. Această practică te ajută să procesezi emoțiile și experiențele tale.",
    "power": "PUTERE",
    "production": "PRODUCȚIE",
    "stackCompleted": "Sesiune Finalizată",
    "reflectionSaved": "Reflecția ta a fost salvată",
    "startNewStack": "Începe o Sesiune Nouă",
    "typeResponse": "Scrie răspunsul tău...",
    "stackHistory": "Istoric Sesiuni",
    "noStackHistory": "Încă nu există istoric sesiuni",
    "completed": "Finalizat",
    "today": "Astăzi",
    "yesterday": "Ieri",
    
    // Trigger responses
    "reflectExperience": "Să reflectăm asupra experienței tale.",
    "thankYouReflection": "Îți mulțumim pentru reflecția ta. Ideile tale au fost salvate în secțiunea COACHING.",
    
    // Button actions
    "view": "VIZUALIZEAZĂ",
    "send": "Trimite",
    
    // Admin panel
    "toolsManagement": "Gestionare Instrumente",
    "addNewTool": "Adaugă Instrument Nou",
    "searchTools": "Caută instrumente...",
    "isActive": "Activ",
    "inactive": "Inactiv",
    "deactivate": "Dezactivează",
    "activate": "Activează",
    "launchTool": "Lansează Instrumentul",
    "launching": "Se lansează",
    "noToolsFound": "Nu s-au găsit instrumente",
    "tryAdjusting": "Încearcă să ajustezi căutarea sau filtrele.",
    
    // Core navigation
    "goToDashboard": "Mergi la Panoul de Control",
    "continue": "Continuă",
    "backToDashboard": "Înapoi la Panoul de Control",
    "core": "NUCLEU",
    
    // Core 4 activities
    "fitness": "FITNESS",
    "fuel": "ALIMENTAȚIE",
    "meditation": "MEDITAȚIE",
    "memoirs": "MEMORII",
    "person1": "PERSOANA 1",
    "person2": "PERSOANA 2",
    "discover": "DESCOPERĂ",
    "declare": "DECLARĂ",
    "thisWeek": "ACEASTĂ SĂPTĂMÂNĂ",
    "body": "CORP",
    "being": "FIINȚĂ",
    "balance": "ECHILIBRU",
    "business": "AFACERI",
    "share": "DISTRIBUIE",
    "activityCompleted": "{activity} finalizat!",
    "activityIncomplete": "{activity} marcat ca nefinalizat",
    "greatJob": "Bună treabă! Progresul tău Core 4 a fost actualizat.",
    "progressUpdated": "Progresul tău a fost actualizat.",
    
    // Dashboard specific
    "trackActivities": "Urmărește Activitățile",
    "myDaily": "ACTIVITĂȚILE MELE ZILNICE",
    "myWeekly": "ACTIVITĂȚILE MELE SĂPTĂMÂNALE",
    "myQuarterly": "ACTIVITĂȚILE MELE TRIMESTRIALE",
    "theMemory": "MEMORIA",
    "theScore": "SCORUL",
    "theStreaks": "SERIILE",
    "theTotal": "TOTALUL",
    "door": "UȘA",
    "game": "JOC",
    "myMissions": "MISIUNILE MELE",
    "warriorBody": "Corp de Războinic",
    "meditationWarrior": "Războinic Meditativ",
    "soulmateFamily": "Familie Sufletească",
    "buildingKingdom": "Construirea Regatului",
    "noStackCompletedYet": "Nu ai finalizat încă stack-ul zilnic.",
    "beginNow": "Începe acum",
    "gratefulMessage": "Sunt recunoscător pentru această nouă oportunitate de a crește.",
    "noDoorTasksYet": "Nu ai setat încă sarcini Domino pentru Ușă.",
    "noTaskSet": "Nicio sarcină setată",
    "setTasks": "Setează Sarcini",
    "viewCoreDetails": "Vezi Detaliile Core",
    
    // Door specific translations
    "commandCenter": "TASKURI",
    "doorTitle": "UȘA",
    "doorPlanningSystem": "Sistem de Planificare Săptămânală", 
    "currentWeek": "Săptămâna Curentă",
    "pastWeek": "Săptămână Trecută",
    "futureWeek": "Săptămână Viitoare",
    "viewingPastWeek": "⚠️ Vizualizezi o săptămână trecută",
    "viewingFutureWeek": "⚠️ Vizualizezi o săptămână viitoare",
    "backToCurrentWeek": "🏠 Înapoi la săptămâna curentă",
    "ideaList": "LISTA DE IDEI",
    "hotList": "LISTA DE IDEI",
    "weeklyGoal": "OBIECTIV SĂPTĂMÂNAL",
    "dominoDoor": "UȘA DOMINO",
    "weeklyMassiveGoal": "OBIECTIV MASIV SĂPTĂMÂNAL",
    "tasks": "SARCINI",
    "todoList": "LISTA DE ACTIVITĂȚI",
    "doList": "LISTA DE FĂCUT",
    "monday": "Luni",
    "tuesday": "Marți",
    "wednesday": "Miercuri",
    "thursday": "Joi",
    "friday": "Vineri",
    "saturday": "Sâmbătă",
    "sunday": "Duminică",
    "mondayShort": "Lun",
    "tuesdayShort": "Mar",
    "wednesdayShort": "Mie",
    "thursdayShort": "Joi",
    "fridayShort": "Vin",
    "saturdayShort": "Sâm",
    "sundayShort": "Dum",
    "noGoalSelected": "Niciun obiectiv selectat încă",
    "dragGoalToSet": "Trage un element din lista de idei pentru a-ți seta obiectivul masiv săptămânal",
    "mainGoal": "Obiectiv Principal:",
    "keyPoints": "Puncte Cheie:",
    "keyPoint": "Punct cheie",
    "noTasksForDay": "Nu există sarcini pentru această zi",
    "noDoItemsForDay": "Nu există elemente DO pentru această zi",
    "dragItemsHere": "Trage elemente aici din lista ta de IDEI",
    "yourIdeaListEmpty": "Lista ta de idei este goală",
    "addNewItemsToStart": "Adaugă elemente noi pentru a începe",
    "addNewIdea": "Adaugă Idee Nouă",
    "addItem": "Adaugă Element",
    "searchItems": "Caută taskuri...",
    "searchIdeas": "Caută idei...",
    "normal": "Normal",
    "important": "Important",
    "urgent": "Urgent",
    "urgentImportant": "Urgent și Important",
    "moveBackToIdeaList": "Mută înapoi în Lista de Idei",
    "moveBackToHotList": "Mută înapoi în Lista Fierbinte",
    "keyPointLabel": "Punct Cheie",
    "todayLabel": "Astăzi",
    "weekLabel": "Săptămâna",
    "autoSaveInfo": "Planificarea săptămânală este salvată automat",
    "enterNewIdea": "Introdu ideea ta nouă...",
    "selectPriority": "Selectează prioritatea",
    "deleteIdea": "Șterge ideea",
    "editIdea": "Editează ideea",
    "weekly": "Săptămânal",
    "planning": "Planificare",
    
    // Fact Maps
    "backToFactMaps": "Înapoi la Hărțile de Fapte",
    "mapOrGoalNotFound": "Harta sau obiectivul nu a fost găsit",
    "enterYourAnswer": "Introduceți răspunsul dvs. aici...",
    "characters": "Caractere",
    "previous": "Anterior",
    "next": "Următorul",
    "reset": "Resetează",
    "save": "Salvează",
    "success": "Succes",
    "answersSaved": "Răspunsurile tale au fost salvate.",
    "stackShared": "Stack Partajat",
    "linkCopiedToClipboard": "Link copiat în clipboard",
    "savedToLibrary": "Salvat în Bibliotecă",
    "savedToLibraryDesc": "Stack-ul tău a fost salvat în bibliotecă",
    "stackLibrary": "Biblioteca de Stack-uri",
    "all": "Toate",
    "shared": "Partajat",
    "noStacksInLibrary": "Nu ai încă stack-uri în bibliotecă",
    "createYourFirstStack": "Creează Primul Tău Stack",
    "errorSaving": "Eroare la Salvare",
    "startOver": "Începe din nou",
    "actionDescription": "Descriere acțiune",
    "addAction": "Adaugă Acțiune",
    "actionAdded": "Acțiune Adăugată",
    "actionAddedDesc": "Acțiunea ta a fost adăugată cu succes",
    "reminderSet": "Reminder Setat",
    "reminderSetDesc": "Vei fi amintit despre această acțiune",
    "actions": "Acțiuni",
    "coaching_completed": "Coaching Finalizat",
    "coaching_completed_desc": "Sesiunea ta de coaching a fost salvată",
    "startNew": "Începe Nou",
    "noCoachingHistoryYet": "Încă nu există istoric de coaching",
    
    // Divine Coaching specific
    "whatAreYouGoingToTitleThisDivineCoaching": "Ce titlu vei da acestei sesiuni de coaching divin?",
    "whoOrWhatAreYouStackingDivine": "Pe cine sau ce te concentrezi?",
    "whyHasThisTriggeredYouToPray": "În acest moment, de ce te-a declanșat să te rogi?",
    "whatIsTheStoryDivineTrigger": "Care este povestea pe care ți-o spui, creată de acest declanșator, despre aceasta și situație?",
    "describeSingleWordFeelingsDivine": "Descrie sentimentele într-un singur cuvânt care apar pentru tine când îți spui acea poveste?",
    "godIsListening": "Dumnezeu ascultă, ce ai de spus?",
    "iWantGODToKnow1": "Doamne, vreau să știu:",
    "iWantGODToKnow2": "Doamne, vreau să știu:",
    "iWantGODToKnow3": "Doamne, vreau să știu:",
    "iWantGODToKnow4": "Doamne, vreau să știu:",
    "dearGODWhatDoYouWantMeToSee": "Dragă DOAMNE, Ce vrei să văd aici?",
    "whatDoYouWantMeToHear": "Ce vrei să aud?",
    "whatDoYouWantMeToLearn": "Ce vrei să învăț?",
    "whatDoYouWantMeToFeel": "Ce vrei să simt?",
    "whatDoYouWantMeToKnow": "Ce vrei să știu?",
    "whatDoYouWantMeToDo": "Ce vrei să fac?",
    "godHeardYou": "Dumnezeu vrea ca tu să:",
    "singularLessonDivine": "Care este lecția singulară despre viață pe care o iei din această sesiune de coaching divin?",
    "howDoesThisLessonApplyToBody": "Cum se aplică această lecție Corpului tău?",
    "howDoesThisLessonApplyToBeing": "Cum se aplică această lecție Ființei tale?",
    "howDoesThisLessonApplyToBalance": "Cum se aplică această lecție Echilibrului tău?",
    "howDoesThisLessonApplyToBusiness": "Cum se aplică această lecție Afacerii tale?",
    "significantRevelationDivine": "Care este cea mai semnificativă revelație sau insight cu care pleci din această sesiune de coaching divin și de ce te simți așa?",
    "immediateActionsDivine": "Ce acțiuni imediate te angajezi să faci când părăsești această sesiune?",
    "doYouWantToAddToHotList": "Vrei să adaugi asta la lista fierbinte?",
    "isThereAnythingElseToAddToHotList": "Mai este ceva ce vrei să adaugi la lista fierbinte?",
    
    // Landing Page - CEO Mind OS
    "jumpToFreedom": "CEO Mind OS",
    "haveItAll": "Ai Tot ce Vrei",
    "startNowSeeResults": "Începe Acum. Vezi Rezultate în 48 de Ore.",
    "freeTrial7Days": "Trial gratuit 7 zile (card necesar). Zero risc. Anulezi oricând în perioada de probă fără taxare.",
    "fifteenMinuteSetup": "Setup de 15 Minute",
    "quickOnboarding": "Onboarding rapid, apoi execuți",
    "resultsIn48h": "Rezultate în 48h",
    "clarityFirstWins": "Claritate + primele victorii",
    "zeroRiskGuarantee": "Garanție Zero Risc",
    "sevenDayTrialCancelFree": "Trial 7 zile, anulezi gratuit",
    "startYour7DayFreeTrial": "Începe Trial-ul Gratuit de 7 Zile",
    "membersTransformed": "500+ membri transformați",
    "averageLifeSatisfaction": "În medie +35% satisfacție în viață în 30 de zile",
    "costOfWaiting": "Costul Așteptării",
    "everyDayWithoutSystem": "Fiecare Zi Fără un Sistem Te Costă",
    "whileYouHesitate": "În timp ce eziti, viața continuă. Iată ce pierzi cu fiecare zi care trece:",
    "bodyEnergyCost": "-0.5% energie și vitalitate",
    "beingPeaceCost": "-1 moment de pace interioară",
    "balanceConnectionCost": "-1 conexiune semnificativă",
    "businessRevenueCost": "-50-500$ venituri potențiale",
    "thirtyDaysFromNow": "Peste 30 de Zile",
    "transformationChoice": "Poți fi fie la 30 de zile în transformarea ta, experimentând mai multă energie, claritate, relații mai bune și venituri în creștere... sau încă te întrebi 'ce-ar fi dacă?'",
    "energyLevel": "Nivel de Energie",
    "mindfulMinutes": "Minute Mindful",
    "qualityMoments": "Momente de Calitate",
    "productivityIncrease": "Productivitate",
    "startMyTransformationToday": "Începe-mi Transformarea Astăzi",
    "averageSetupTime": "Timp mediu de setup: 15 minute",
    "aboutJumpToFreedom": "Despre CEO Mind OS",
    "ourMissionValues": "Misiunea și Valorile Noastre",
    "aboutDescription": "Află despre misiunea CEO Mind OS de a te ajuta să atingi succesul holistic în Corp, Ființă, Echilibru și Afaceri prin sisteme dovedite și obiceiuri zilnice.",
    "missionToHelpYou": "Suntem pe o misiune de a te ajuta să te eliberezi din capcana dezechilibrului și să construiești o viață în care ai cu adevărat totul - sănătate, pace, iubire și prosperitate.",
    "storyBehind": "Povestea din Spatele CEO Mind OS",
    "purposeDriven": "Orientat spre Scop",
    "purposeDrivenDesc": "Fiecare funcționalitate este concepută pentru a te ajuta să trăiești cu intenție și să atingi obiective semnificative în toate ariile vieții.",
    "holisticGrowth": "Creștere Holistică",
    "holisticGrowthDesc": "Credem că adevăratul succes vine din echilibru - hrănind corpul, mintea, relațiile și cariera împreună.",
    "continuousImprovement": "Îmbunătățire Continuă",
    "continuousImprovementDesc": "Acțiunile zilnice mici se acumulează în rezultate extraordinare. Te ajutăm să construiești sisteme, nu doar motivație.",
    "communitySupport": "Suport din Comunitate",
    "communitySupportDesc": "Nu ești singur în această călătorie. Conectează-te cu oameni care gândesc la fel și sunt dedicați creșterii.",
    "fourPillarsOfFreedom": "Cei 4 Piloni ai Libertății",
    "trueFreedomComes": "Adevărata libertate vine din măiestria în toate cele patru arii ale vieții. Neglijează una, și celelalte vor suferi eventual.",
    "bodyPillarDesc": "Sănătate fizică, energie, fitness și vitalitate",
    "beingPillarDesc": "Claritate mentală, spiritualitate și pace interioară",
    "balancePillarDesc": "Relații, familie și conexiuni semnificative",
    "businessPillarDesc": "Creștere în carieră, finanțe și succes profesional",
    "ourMission": "Misiunea Noastră",
    "missionStatement": "Să împuternicim 1 milion de oameni să se elibereze din capcana vieții dezechilibrate și să construiască vieți de abundență holistică.",
    "ourVision": "Viziunea Noastră",
    "visionStatement": "O lume în care succesul este măsurat nu prin realizări izolate, ci prin armonie și împlinire în toate dimensiunile vieții.",
    "ourCoreValues": "Valorile Noastre de Bază",
    "coreValuesPrinciples": "Aceste principii ghidează tot ce construim și fiecare decizie pe care o luăm.",
    "readyToJump": "Ești Gata să Începi cu CEO Mind OS?",
    "joinThousands": "Alătură-te miilor de oameni care și-au transformat viețile prin stăpânirea tuturor celor patru piloni. Începe trial-ul gratuit de 7 zile astăzi.",
    "startFreeTrial": "Începe Trial Gratuit",
    "learnMore": "Află Mai Multe",
    
    // XP System translations
    "level": "Nivel",
    "xp": "XP",
    "xpToNextLevel": "XP pentru nivelul următor",
    "totalXP": "XP Total",
    "levelUp": "Nivel Nou!",
    "levelUpCongrats": "Felicitări!",
    "youReachedLevel": "Ai ajuns la nivelul",
    "keepGoing": "Continuă! Lucruri mărețe te așteaptă.",
    "continueJourney": "Continuă Călătoria",
    "xpEarned": "XP câștigat",
    
    // Level titles
    "levelTitle_1": "Căutător Trezit",
    "levelTitle_2": "Inițiat Concentrat",
    "levelTitle_3": "Războinic Disciplinat",
    "levelTitle_4": "Campion în Ascensiune",
    "levelTitle_5": "Maestru Luminat",
    "levelTitle_6": "Înțelept Sage",
    "levelTitle_7": "Erou Legendar",
    "levelTitle_8": "Ființă Transcendentă",
    "levelTitle_9": "Războinic Cosmic",
    "levelTitle_10": "Maestru Infinit",
    
    // Daily Challenges
    "dailyChallenges": "Provocări Zilnice",
    "challengeProgress": "Progres",
    "claimReward": "Revendică Recompensa",
    "challengeCompleted": "Finalizat!",
    "challengesRefreshIn": "Provocările se reînnoiesc în",
    "allChallengesComplete": "Toate provocările completate! Bună treabă!",
    "hours": "ore",
    "minutes": "minute",
    
    // Challenge types
    "challenge_complete_stack": "Finalizează un Stack",
    "challenge_complete_stack_desc": "Termină o sesiune de reflecție",
    "challenge_read_pages": "Citește Pagini",
    "challenge_read_pages_desc": "Citește cel puțin 5 pagini astăzi",
    "challenge_complete_core": "Finalizează Core 4",
    "challenge_complete_core_desc": "Completează toate activitățile Core 4",
    "challenge_complete_actions": "Completează Acțiuni",
    "challenge_complete_actions_desc": "Finalizează 3 elemente de acțiune",
    "challenge_login_streak": "Serie de Conectări",
    "challenge_login_streak_desc": "Menține seria ta",
    "challenge_complete_door": "Sarcini Door",
    "challenge_complete_door_desc": "Finalizează 5 sarcini door",
    
    // Smart Notifications
    "goodMorning": "Bună Dimineața!",
    "goodAfternoon": "Bună Ziua!",
    "goodEvening": "Bună Seara!",
    "streakAtRisk": "Seria ta este în pericol!",
    "streakAtRiskDesc": "Finalizează o activitate pentru a-ți menține seria",
    "almostLevelUp": "Aproape ai ajuns!",
    "almostLevelUpDesc": "Doar {xp} XP până la nivelul următor!",
    "welcomeBack": "Bine ai revenit!",
    "welcomeBackDesc": "Gata să continui călătoria?",
    "greatStreak": "Serie incredibilă!",
    "greatStreakDesc": "{days} zile și continuăm!",
    "startSession": "Începe Sesiunea",
    "viewProgress": "Vezi Progresul",
    
    // Streak Milestones
    "streakMilestone": "Milestone Serie!",
    "days": "zile",
    "dayStreak": "Zile Consecutive",
    "streakBonus": "Bonus Serie",
    "streakShieldUnlocked": "Scut Serie Deblocat!",
    "streakShieldDesc": "Acum ai protecție împotriva pierderii seriei",
    "keepItUp": "Continuă Așa!",
    
    // Streak milestone titles
    "streak_7_title": "Războinic de O Săptămână",
    "streak_7_subtitle": "7 zile de dedicare",
    "streak_7_message": "Ai arătat un angajament real. Obiceiul se formează!",
    "streak_30_title": "Maestru Lunar",
    "streak_30_subtitle": "30 de zile de disciplină",
    "streak_30_message": "O lună întreagă! Construiești ceva extraordinar.",
    "streak_100_title": "Campion Centenar",
    "streak_100_subtitle": "100 de zile de excelență",
    "streak_100_message": "100 de zile de creștere. Ești cu adevărat de neoprit!",
    "streak_365_title": "Legendă Anuală",
    "streak_365_subtitle": "365 de zile de măiestrie",
    "streak_365_message": "Un an întreg! Ai atins statutul de legendă.",
    
    // Badge Unlock
    "badgeUnlocked": "Insignă Deblocată!",
    "newBadge": "Insignă Nouă",
    "awesome": "Excelent!",
    
    // Weekly Recap
    "weeklyRecap": "Rezumatul Săptămânii",
    "weekNumber": "Săptămâna",
    "daysActive": "Zile Active",
    "daysActiveSubtitle": "Ai fost prezent săptămâna aceasta!",
    "stacksCompleted": "Stack-uri Finalizate",
    "stacksCompletedSubtitle": "Sesiuni de reflecție completate",
    "pagesRead": "Pagini Citite",
    "pagesReadSubtitle": "Cunoștințe acumulate",
    "actionsCompleted": "Acțiuni Finalizate",
    "actionsCompletedSubtitle": "Sarcini îndeplinite",
    "xpEarnedWeek": "XP Câștigat",
    "xpEarnedSubtitle": "Experiență acumulată",
    "currentStreakWeek": "Serie Curentă",
    "currentStreakSubtitle": "Zile consecutive",
    "badgesEarned": "Insigne Câștigate",
    "badgesEarnedSubtitle": "Realizări deblocate",
    "greatWeek": "Săptămână excelentă!",
    "seeYouNextWeek": "Ne vedem săptămâna viitoare!",
    
    // Milestone Celebrations
    "milestoneReached": "Milestone Atins!",
    "firstStack": "Primul Stack",
    "firstStackMessage": "Ai finalizat primul tău stack de reflecție!",
    "tenStacks": "10 Stack-uri",
    "tenStacksMessage": "Un milestone al reflecției și creșterii!",
    "hundredPages": "100 de Pagini",
    "hundredPagesMessage": "Ai citit 100 de pagini de înțelepciune!",
    "firstWeek": "Prima Săptămână",
    "firstWeekMessage": "Prima ta serie de o săptămână!",
    "firstMonth": "Prima Lună",
    "firstMonthMessage": "O lună întreagă de dedicare!",
    "levelFive": "Nivelul 5",
    "levelFiveMessage": "Ai ajuns la Nivelul 5!",
    "levelTen": "Nivelul 10",
    "levelTenMessage": "Marele 10! Ești un maestru!",
    
    // Rewards Showcase
    "rewards": "Recompense",
    "unlockableRewards": "Recompense Deblocabile",
    "themes": "Teme",
    "avatars": "Avataruri",
    "frames": "Rame",
    "unlockAt": "Deblochează la Nivelul",
    "unlocked": "Deblocat",
    "equipped": "Echipat",
    "equip": "Echipează",
    "locked": "Blocat",
    "nextReward": "Următoarea Recompensă",
    
    // Reward names
    "reward_dark_theme": "Tema Războinic Întunecat",
    "reward_dark_theme_desc": "O temă întunecată elegantă pentru războinici concentrați",
    "reward_gold_theme": "Tema Campion Auriu",
    "reward_gold_theme_desc": "O temă aurie prestigioasă",
    "reward_nature_theme": "Tema Armonie Naturală",
    "reward_nature_theme_desc": "Culori liniștitoare inspirate de natură",
    "reward_avatar_warrior": "Avatar Războinic",
    "reward_avatar_warrior_desc": "Avatarul clasic al războinicului",
    "reward_avatar_sage": "Avatar Înțelept",
    "reward_avatar_sage_desc": "Înțelepciunea personificată",
    "reward_avatar_legend": "Avatar Legendă",
    "reward_avatar_legend_desc": "Pentru realizatorii legendari",
    "reward_frame_bronze": "Ramă de Bronz",
    "reward_frame_bronze_desc": "O ramă solidă de bronz",
    "reward_frame_silver": "Ramă de Argint",
    "reward_frame_silver_desc": "O ramă elegantă de argint",
    "reward_frame_gold": "Ramă de Aur",
    "reward_frame_gold_desc": "Prestigioasa ramă de aur",
    
    // Gamification general
    "gamification": "Gamificare",
    "achievements": "Realizări",
    "progress": "Progres",
    "streak": "Serie",
    "currentStreak": "Serie Curentă",
    "longestStreak": "Cea Mai Lungă Serie",
    "totalDaysActive": "Total Zile Active",
    "loading": "Se încarcă...",
    "error": "Eroare",
    "close": "Închide",
    "ok": "OK",
    "cancel": "Anulează",
    "confirm": "Confirmă",
    "delete": "Șterge",
    "edit": "Editează",
    "add": "Adaugă",
    "remove": "Elimină",
    "update": "Actualizează",
    
    // DailyCompactCard
    "dailyPage": "Pagina Zilnică",
    "read": "Citit",
    "pleaseLoginToTrack": "Te rugăm să te autentifici pentru a urmări progresul",
    "actionCompletedToast": "Acțiune finalizată!",
    "showMore": "Arată mai mult",
    "showLess": "Arată mai puțin",
    "create": "Creează",
    "submit": "Trimite",
    "done": "Gata",
    "finish": "Finalizează",
    "start": "Începe",
    "stop": "Oprește",
    "pause": "Pauză",
    "resume": "Reia",
    "retry": "Încearcă din nou",
    "back": "Înapoi",
    "forward": "Înainte",
    "yes": "Da",
    "no": "Nu",
    
    // Biz 4 translations
    "biz4": "BIZ 4",
    "dailyFour": "BIZ 4",
    "weeklyTwo": "WEEKLY TWO",
    "contentDesc": "Creează 1 piesă de conținut",
    "engageDesc": "Interacționează cu audiența",
    "outreachDesc": "Contactează prospecți noi",
    "closeDesc": "Conversație de vânzare/follow-up",
    "podcastDesc": "Înregistrează episodul săptămânal",
    "webinarDesc": "Ține webinarul/live-ul săptămânal",
    
    // Menu items - CEO Mind OS Rebrand
    "aiCoaches": "Antrenori AI",
    "lifeVision": "Viziunea Vieții",
    "ninetyDayChallenge": "Provocarea de 90 Zile",
    "dailyPlanner": "Planificator Zilnic",
    "businessCoach": "Antrenor Business",
    "successCoach": "Principii de Succes",
    "mindsetCoach": "Antrenor Mindset",
    "lifeCoach": "Antrenor de Viață",
    "emotionCoach": "Antrenor Emoțional",
    "gratitudeJournal": "Jurnal de Recunoștință",
    "businessTracker": "Tracker Business",
    "learningHub": "Hub de Învățare",
    "masteryProgram": "Program de Măiestrie",
    "weeklyGoals": "Obiective Săptămânale",
    "todaysFocus": "Focusul de Azi",
    "dailyRoutine": "Rutina Zilnică",
    
    // Legacy menu items (kept for compatibility)
    "haveItAllBlueprint": "📖 Viziunea Vieții",
    "haveItAllChallenge": "🚀 Provocarea de 90 Zile",
    "masterPlan": "📚 Principii de Succes",
    "myProjects": "Proiectele Mele",
    "activeJourney": "Călătoria Activă",
    "knowledgeBase": "Baza de Cunoștințe",
    "dailyMasterStack": "Planificator Zilnic",
    "angerAlchemy": "Antrenor Emoțional",
    "divineGratitude": "Mindset și Recunoștință",
    "divineConnection": "Antrenor Mindset",
    "gratitudePractice": "Jurnal de Recunoștință",
    "principleCoaching": "Antrenor Succes",
    "wisdomOracle": "Antrenor de Viață",
    "businessEmpire": "Antrenor Business",
    "mastersAcademy": "Program de Măiestrie",
    "reflectionJournal": "Jurnal de Reflecție",
    "voiceAnalysis": "Analiză Vocală",
    "transformationToolkit": "Antrenori AI",
    "freedomMissions": "Misiuni pentru Libertate",
    "notes": "Notițe",
    "library": "Bibliotecă",
    "subscriptions": "Abonamente",
    "admin": "Admin",
    "settings": "Setări",
    "support": "Suport",
    
    // DoorHeader
    "history": "Istoric",
    "deleteBtn": "Șterge",
    "cleanDuplicates": "Curăță Dublurile",
    "clearWeek": "Șterge Săptămâna",
    "deleteHistory": "Șterge Istoric",
    "undoCtrl": "Anulează (Ctrl+Z)",
    "redoCtrl": "Refă (Ctrl+Shift+Z)",
    
    // VoiceLanguageToggle
    "voiceRecognitionLanguage": "Limbă recunoaștere vocală",
    "clickToChange": "Click pentru a schimba",
    
    // Index.tsx Meta tags
    "indexMetaTitle": "CEO Mind OS — Succes Fără Sacrificiu: Sistemul de Operare pentru Fondatori, cu AI",
    "indexMetaDescription": "CEO Mind OS este sistemul de operare pentru fondatori, alimentat de AI, care ajută antreprenorii să-și crească afacerea FĂRĂ să-și piardă sănătatea, relațiile sau pacea sufletească. Transformă toate cele 4 arii ale vieții simultan.",
    
    // HeroSection.tsx
    "heroSuccess": "Succes",
    "heroWithout": "Fără",
    "heroSacrifice": "Sacrificiu",
    "heroSubtitle": "Sistemul AI complet pentru antreprenori care vor TOT: corp sănătos, relații puternice, claritate interioară ȘI business profitabil.",
    "heroFeature1": "4 Coachi AI (Corp, Mindset, Relații, Business)",
    "heroFeature2": "Rutina Războinicului - 30 min/zi care schimbă totul",
    "heroFeature3": "The Door - Sistem de planificare săptămânală inteligent",
    "heroLogin": "Autentificare",
    "heroStartFreeTrial": "Încearcă Gratuit",
    "heroStart3DayTrial": "Încearcă 3 Zile Gratuit",
    "heroSeeHowItWorks": "Vezi Cum Funcționează",
    "hero4LifeAreas": "4 Arii de Viață Integrate",
    "hero90DayGuarantee": "Garanție 90 Zile",
    "heroCancelAnytime": "Anulezi Oricând",
    "heroVideoCaption": "Vezi: Cum CEO Mind OS transformă antreprenorii în 90 de zile",
    "heroUsedBy": "Folosit de antreprenori din E-commerce, SaaS, Consulting, Imobiliare",
    
    // ChampionRoutine STEP_LABELS
    "stepEmotionalCheck": "Check-in Emoțional",
    "stepStackSelection": "Alege Stack-ul",
    "stepEmotionalTransform": "Transformare Emoțională",
    "stepGratitude": "Recunoștință",
    "stepHydration": "Hidratare",
    "stepMeditation": "Meditație",
    "stepAutosuggestion": "Autosugestie",
    "stepVisionDeclaration": "Declarație Viziune",
    "stepExercise": "Exerciții",
    "stepMealPlanning": "Planificare Mese",
    "stepContentCreation": "Creație Conținut",
    "stepDailyTasks": "Taskuri Zilnice",
    "stepRelationships": "Relații",
    "stepBreathing": "Respirație",
    "stepVisualization": "Vizualizare",
    "stepReading": "Citit",
    "stepJournaling": "Jurnalizare",
    "stepLightExposure": "Lumină Naturală",
    "stepLearn": "Învață",
    "stepApply": "Aplică/Predă",
    "stepHabitBody": "Obiceiuri: Corp",
    "stepHabitBeing": "Obiceiuri: Spirit",
    "stepHabitBalance": "Obiceiuri: Relații",
    "stepHabitBusiness": "Obiceiuri: Business",
    "stepTodaysTasks": "Sarcinile de Azi",
    "stepCompletion": "Finalizare",
    
    // Footer links
    "footerPricing": "Prețuri",
    "footerTerms": "Termeni și Condiții",
    "footerPrivacy": "Politica de Confidențialitate",
    "footerSupport": "Suport",
    "footerLogin": "Autentificare",
    "footerAllRightsReserved": "Toate drepturile rezervate.",
    
    // Landing Page Hero - CEO Mind OS Rebrand
    "landingHeroTitle": "<span>Succes Fără Sacrificiu.</span>",
    "landingHeroTitlePart2": "Sistemul de Operare pentru Fondatori, cu AI",
    "landingHeroDesc": "<span>CEO Mind OS</span> ajută antreprenorii să își crească afacerea <span>FĂRĂ</span> să își piardă sănătatea, relațiile sau pacea sufletească — transformă-te din copleșit în împlinit",
    "landingHeroTrusted": "De încredere pentru <span>65.000+ oameni de succes din 40+ țări</span> • Ghidare AI pentru <span>Corp, Ființă, Echilibru & Afaceri</span> • Primele rezultate în <span>48 de ore</span>",
    "landingStartTrial": "Începe Trial de 3 Zile",
    "landingSeePricing": "Vezi Pricing & ROI",
    "landingTransformIn4Areas": "Transformare în 4 arii",
    "landingCompleteLifeSystem": "Sistem complet de viață",
    "landing3DayFreeTrial": "Trial 3 zile gratuit",
    "landingVideoCaption": "🎬 Vezi cum funcționează sistemul în practică",
    "landingAlreadyHaveAccount": "Ai deja cont?",
    "landingAuthenticate": "Autentificare",
    
    // Landing Page - Pit Section
    "landingPitTitle": "Ești Blocat în Groapă?",
    "landingPitSubtitle": "Groapa Dezechilibrului are 5 semne de avertizare. Bifează ce rezonează cu tine:",
    "landingPitWorkConstantly": "Lucrez constant dar rezultatele nu vin",
    "landingPitWorkConsequence": "→ Burnout garantat în 6-12 luni, colapsul afacerii",
    "landingPitDisconnected": "Mă simt deconectat de familia/partenerul meu",
    "landingPitDisconnectedConsequence": "→ Divorț sau relații distruse, copii care suferă",
    "landingPitBodySuffering": "Corpul meu suferă (oboseală, creștere în greutate, fără energie)",
    "landingPitBodyConsequence": "→ Boală cronică, epuizare fizică, risc cardiac",
    "landingPitNumb": "Mă anestezez cu mâncare/alcool/social media",
    "landingPitNumbConsequence": "→ Dependențe, depresie, pierderea identității",
    "landingPitDeserve": "Simt că nu merit mai mult",
    "landingPitDeserveConsequence": "→ Auto-sabotaj perpetuu, nu îți atingi niciodată potențialul",
    "landingPitChecked": "Ai bifat {count} din 5 — Ești în Groapă.",
    "landingPitGoodNews": "Vestea bună? <span>Există o cale de ieșire.</span> CEO Mind OS te învață cum să scapi din Groapă și să construiești echilibru real în Corp, Ființă, Echilibru & Afaceri.",
    "landingPitCloseToEdge": "Ești aproape de marginea Gropii. Acum e timpul să construiești un sistem care <span>te protejează și te pune pe calea creșterii.</span>",
    "landingPitExcellent": "Excelent că nu rezonezi cu aceste simptome! Totuși, CEO Mind OS te învață <span>cum să PROTEJEZI</span> ce ai construit și <span>să SCALEZI</span> fără să sacrifici nimic.",
    
    // Landing Page - Unique Mechanism
    "landing5Pillars": "Cele 5 Piloni ai Libertății",
    "landing5PillarsDesc": "Nu e un tool de productivitate. E un <span>sistem complet de viață</span> care integrează Corp, Ființă, Echilibru și Afaceri într-un cadru unificat.",
    "landingBodyDesc": "Ritualuri zilnice de mișcare și nutriție",
    "landingBodyResult": "Energie, forță, vitalitate",
    "landingBeingDesc": "Meditație, Stack și claritate interioară",
    "landingBeingResult": "Pace, scop, putere mentală",
    "landingBalanceDesc": "Adăugare de valoare în relații zilnic",
    "landingBalanceResult": "Conexiuni profunde, iubire, moștenire",
    "landingBusinessDesc": "Învățare strategică și aplicare",
    "landingBusinessResult": "Creștere, venit, impact",
    "landingDoorTitle": "Ușa",
    "landingDoorDesc": "Planificare și execuție săptămânală",
    "landingDoorResult": "Focus pe ce contează cu adevărat",
    "landingSystemTitle": "Funcționează Împreună ca UN SISTEM",
    "landingSystemDesc": "Fiecare pilon se conectează cu ceilalți. Corpul îți dă energie. Ființa îți dă claritate. Echilibrul te menține stabil. Afacerile conduc creșterea. Ușa te ține focusat săptămânal. <span>Unul fără ceilalți duce la dezechilibru.</span>",
    
    // Landing Page - Urgency Section
    "landingCostOfWaiting": "Costul Așteptării",
    "landingEveryDayWithout": "Fiecare Zi Fără un Sistem Te Costă",
    "landingWhileYouHesitate": "În timp ce eziti, viața continuă să meargă. Iată ce pierzi cu fiecare zi care trece:",
    "landingBodyCost": "-0.5% energie și vitalitate în fiecare zi când sari peste rutina de sănătate",
    "landingBeingCost": "-1 moment de pace interioară pierdut din cauza stresului și a ceții mentale",
    "landingBalanceCost": "-1 conexiune semnificativă cu cei dragi pe care nu o vei mai recupera",
    "landingBusinessCost": "-50-500$ venit potențial din oportunități ratate și haos",
    "landing30DaysFromNow": "Peste 30 de Zile",
    "landing30DaysDesc": "Poți fi fie cu 30 de zile în transformarea ta, experimentând mai multă energie, claritate, relații mai bune și venituri în creștere... fie încă întrebându-te \"ce-ar fi dacă?\"",
    "landingEnergyLevel": "Nivel de Energie",
    "landingMindfulMinutes": "Minute de Mindfulness",
    "landingQualityMoments": "Momente de Calitate",
    "landingProductivity": "Productivitate",
    "landingStartTransformation": "Începe-mi Transformarea Azi",
    "landingAverageSetupTime": "Timp mediu de configurare: 15 minute",
    
    // Landing Page - For Whom Section
    "landingForWhomTitle": "Este CEO Mind OS Potrivit pentru Tine?",
    "landingForWhomSubtitle": "Fii sincer cu tine: dacă te vezi în coloana din stânga, asta e pentru tine. Dacă ești în coloana din dreapta, <span>nu e încă</span> momentul potrivit.",
    "landingIsForYou": "CEO Mind OS ESTE pentru tine dacă:",
    "landingNotForYou": "CEO Mind OS NU este pentru tine dacă:",
    "landingIdeal1": "Vrei să ai TOTUL — nu doar bani, ci sănătate, relații și pace interioară",
    "landingIdeal2": "Ești dispus să confrunți adevărul despre viața ta actuală",
    "landingIdeal3": "Vrei un sistem structurat, nu motivație de weekend",
    "landingIdeal4": "Înțelegi că schimbarea reală necesită timp, energie și angajament",
    "landingIdeal5": "Vrei să lași o moștenire copiilor tăi — un exemplu de om complet",
    "landingNot1": "Cauți o soluție rapidă sau un 'hack' magic",
    "landingNot2": "Nu ești dispus să faci munca zilnică",
    "landingNot3": "Vrei doar bani, fără echilibru în corp, relații sau spirit",
    "landingNot4": "Crezi că știi deja totul și nu ai nevoie de un sistem",
    "landingNot5": "Nu ești dispus să spui adevărul despre unde ești acum",
    "landingIdealSummary": "<span>Pe scurt:</span> Vrei un corp sănătos, relații puternice, claritate spirituală ȘI o afacere profitabilă — și ești gata să urmezi un sistem complet.",
    "landingNotSummary": "<span>Pe scurt:</span> Dacă vrei doar bani fără echilibru sau cauți scurtături, CEO Mind OS nu e pentru tine. Revino când ești gata pentru transformare completă.",
    "landingForWhomFooter": "Dacă te vezi în coloana verde, începe trial-ul gratuit. Dacă ești în roșu, salvează această pagină și revino când ești pregătit.",
    "landingForWhomFooterHighlight": "CEO Mind OS funcționează doar pentru cei care sunt cu adevărat gata să se transforme.",
    
    // Landing Page - Founder Section
    "landingFounderTitle": "De Ce Am Creat CEO Mind OS",
    "landingFounderSubtitle": "Povestea din spatele sistemului care transformă antreprenorii blocați în lideri echilibrați",
    "landingFounderName": "[Nume Fondator]",
    "landingFounderRole": "Fondator, CEO Mind OS",
    "landingFounderYears": "<span>7 ani.</span> Mi-au trebuit 7 ani să descopăr, testez și dovedesc calea către libertatea adevărată.",
    "landingFounderStory1": "În 2016, aveam \"totul\": venituri de €1M+, echipă de 15, birouri frumoase. Dar realitatea? <span>Burnout complet, 105 kg, anxietate cronică, o soție pe care o vedeam 2 ore pe săptămână</span>.",
    "landingFounderStory2": "Am ajuns la spital după un atac de anxietate. Doctorii mi-au spus: <span>\"Dacă nu schimbi ceva radical, nu mai ai mult timp.\"</span> Aveam 32 de ani și eram gata să mor.",
    "landingFounderStory3": "Am realizat adevărul brutal: <span>Aveam bani, dar nu aveam VIAȚĂ</span>. Corpul meu se prăbușea. Relația cu soția era moartă. Nu simțeam nimic spiritual. Afacerea mergea, dar eu eram o ruină umană.",
    "landingFounderStory4": "Am refuzat să accept că acesta era sfârșitul. Am început să caut răspunsuri — nu în pastile sau motivație de weekend, ci în <span>adevărul brutal</span>. Am realizat că problema nu era doar în afaceri. Era în <span>TOATE ariile simultan</span> — corp, spirit, relații, afaceri.",
    "landingFounderResultsTitle": "Rezultatele transformării:",
    "landingFounderResult1": "Am slăbit 30 kg în 4 luni",
    "landingFounderResult2": "De la depresie la putere mentală și claritate",
    "landingFounderResult3": "Afacerea a crescut la €5M+ în 3 ani",
    "landingFounderResult4": "De la relație toxică la căsătorie pasională",
    "landingFounderResult5": "Tată și soț ghidat de credință",
    "landingFounderConclusion1": "<span>Succesul fără echilibru e doar o altă formă de sărăcie.</span> Poți avea milioane în bancă și tot să fii în Groapă — deconectat, desensibilizat, distrus în interior. Eu am fost acolo. <span>Nu vreau ca alți bărbați să ajungă unde am fost eu.</span>",
    "landingFounderConclusion2": "Am sistematizat tot ce am învățat în acei 7 ani și l-am transformat în CEO Mind OS. Nu pentru că vreau să vând ceva — pentru că <span>nu am avut pe nimeni să-mi arate calea când eram în Groapă</span>. Și cunosc acea durere. <span>Tu ai acum șansa pe care eu nu am avut-o niciodată.</span>",
    "landingFounderStats": "Acum sistemul este folosit de 65.000+ bărbați în 40+ țări. Construit pe principii atemporale, adaptat pentru viața modernă.",
    
    // Landing Page - Final CTA
    "landingFinalCTATitle": "Începe Acum. Vezi Rezultate în 48 de Ore.",
    "landingFinalCTASubtitle": "Trial gratuit de 3 zile (card necesar). Zero risc. Anulează oricând în timpul trial-ului fără taxe.",
    "landing15MinSetup": "Configurare în 15 Minute",
    "landingQuickOnboarding": "Onboarding rapid, apoi execuți",
    "landingResultsIn48h": "Rezultate în 48h",
    "landingClarityFirstWins": "Claritate + primele victorii",
    "landingZeroRiskGuarantee": "Garanție Zero Risc",
    "landing3DayTrialCancelFree": "Trial 3 zile, anulare gratuită",
    "landingStartFreeTrial": "Începe Trial-ul Gratuit de 3 Zile",
    "landingMembersStats": "500+ membri transformați • Media +35% satisfacție de viață în 30 zile • Trial 3 zile gratuit",
    "landingPlanYour2026": "Sau planifică-ți 2026 gratuit"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  isLoading: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'ro',
  setLanguage: () => {},
  t: (key: string) => key,
  isLoading: true,
});

export const LanguageProvider: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  // Initialize with language from localStorage, defaulting to 'ro'
  const getInitialLanguage = (): Language => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return (savedLanguage === 'en' || savedLanguage === 'ro') ? savedLanguage : 'ro';
  };
  
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);
  const [isLoading, setIsLoading] = useState(true);
  const [userId, setUserId] = useState<string | null>(null);

  // Listen for auth state changes
  useEffect(() => {
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      setUserId(session?.user?.id ?? null);
    });

    // Check for existing session
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUserId(session?.user?.id ?? null);
    });

    return () => subscription.unsubscribe();
  }, []);

  // Load language preference from database when user is authenticated
  useEffect(() => {
    const loadLanguageFromDB = async () => {
      if (!userId) {
        setIsLoading(false);
        return;
      }

      try {
        const { data, error } = await supabase
          .from('user_preferences')
          .select('language')
          .eq('user_id', userId)
          .maybeSingle();

        if (error) {
          console.error('Error loading language preference:', error);
          setIsLoading(false);
          return;
        }

        if (data?.language && (data.language === 'en' || data.language === 'ro')) {
          setLanguageState(data.language as Language);
          localStorage.setItem('language', data.language);
        }
      } catch (err) {
        console.error('Error loading language preference:', err);
      } finally {
        setIsLoading(false);
      }
    };

    loadLanguageFromDB();
  }, [userId]);

  // Update language in both localStorage and database
  const setLanguage = useCallback(async (newLanguage: Language) => {
    // Update local state immediately
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);

    // If user is authenticated, save to database
    if (userId) {
      try {
        const { error } = await supabase
          .from('user_preferences')
          .upsert(
            { 
              user_id: userId, 
              language: newLanguage,
              updated_at: new Date().toISOString()
            },
            { 
              onConflict: 'user_id' 
            }
          );

        if (error) {
          console.error('Error saving language preference:', error);
        }
      } catch (err) {
        console.error('Error saving language preference:', err);
      }
    }
  }, [userId]);

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['ro'][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLoading }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
