// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in CEO Mind OS user's id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = { userId: ctx.getUserId(), email: ctx.getUserEmail() ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-notes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_notes_default = defineTool2({
  name: "list_notes",
  title: "List notes",
  description: "List the signed-in user's notes, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max notes to return (default 20)."),
    category: z.string().optional().describe("Filter by category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("notes").select("id,title,content,category,pinned,created_at,updated_at").order("pinned", { ascending: false }).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-note.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_note_default = defineTool3({
  name: "create_note",
  title: "Create note",
  description: "Create a new note for the signed-in CEO Mind OS user.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Note title."),
    content: z2.string().optional().describe("Note body."),
    category: z2.string().optional().describe("Optional category label."),
    pinned: z2.boolean().optional().describe("Pin the note to the top.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, content, category, pinned }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("notes").insert({
      user_id: ctx.getUserId(),
      title,
      content: content ?? "",
      category: category ?? null,
      pinned: pinned ?? false
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_journal_entries_default = defineTool4({
  name: "list_journal_entries",
  title: "List journal entries",
  description: "List the signed-in user's journal entries, most recent first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max entries to return (default 10)."),
    from_date: z3.string().optional().describe("Include entries with entry_date >= this ISO date (YYYY-MM-DD)."),
    to_date: z3.string().optional().describe("Include entries with entry_date <= this ISO date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("journal_entries").select("id,title,content,lesson,entry_date,created_at,updated_at").order("entry_date", { ascending: false }).limit(limit ?? 10);
    if (from_date) q = q.gte("entry_date", from_date);
    if (to_date) q = q.lte("entry_date", to_date);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_journal_entry_default = defineTool5({
  name: "create_journal_entry",
  title: "Create journal entry",
  description: "Create a journal entry for the signed-in CEO Mind OS user.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Entry title."),
    content: z4.string().optional().describe("Journal body / reflection."),
    lesson: z4.string().optional().describe("Key lesson or insight."),
    entry_date: z4.string().optional().describe("Date of the entry (YYYY-MM-DD). Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, content, lesson, entry_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const date = entry_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser4(ctx).from("journal_entries").insert({
      user_id: ctx.getUserId(),
      title,
      content: content ?? "",
      lesson: lesson ?? null,
      entry_date: date
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "exsbnfmaadjyfblperas";
var mcp_default = defineMcp({
  name: "ceo-mind-os-mcp",
  title: "CEO Mind OS",
  version: "0.1.0",
  instructions: "Tools for CEO Mind OS \u2014 the Founder Operating System. Use `whoami` to verify the connection, `list_notes` / `create_note` to work with the user's notes, and `list_journal_entries` / `create_journal_entry` to work with journal entries. All tools act as the signed-in user; data is scoped by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_notes_default, create_note_default, list_journal_entries_default, create_journal_entry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
