// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwmtuyivzacrioyerpgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bXR1eWl2emFjcmlveWVycGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTI3NzQsImV4cCI6MjA1OTU4ODc3NH0.8xyu5xsb9z5Iiaf55pfasifh2hYZ8oR06iodIZ8SHDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);